<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="8.0.22" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../database/schema.sql" Link="Schema/schema.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\IMS.Application\IMS.Application.csproj" />
    <ProjectReference Include="..\..\src\IMS.API\IMS.API.csproj" />
    <ProjectReference Include="..\..\src\IMS.Domain\IMS.Domain.csproj" />
    <ProjectReference Include="..\..\src\IMS.Infrastructure\IMS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
