import { useEffect, useState, type FormEvent } from 'react';
import { ApiError } from '../api/client';
import { getCustomers } from '../api/customers';
import { getGuarantors } from '../api/guarantors';
import { getProducts } from '../api/products';
import type { Customer } from '../types/customers';
import type { ContractRequest } from '../types/contracts';
import type { Guarantor } from '../types/guarantors';
import type { Product } from '../types/products';
import { formatMoney } from '../utils/format';

type DraftItem = { product: Product; quantity: string; unitPrice: string };
type Props = { token: string; onSubmit(request: ContractRequest): Promise<void> };
const moneyPattern = /^\d+(?:\.\d{1,2})?$/;
function validMoney(value: string) { if (!moneyPattern.test(value)) return false; const whole = value.split('.')[0].replace(/^0+(?=\d)/, ''); return whole.length < 13 || whole.length === 13 && whole <= '9999999999999'; }
function errorLines(errors: Record<string, string[]>) { return Object.entries(errors).flatMap(([field, messages]) => messages.map(message => `${field}: ${message}`)); }

export function ContractForm({ token, onSubmit }: Props) {
  const [contractNumber, setContractNumber] = useState(''); const [contractDate, setContractDate] = useState(''); const [downPayment, setDownPayment] = useState(''); const [guaranteeNotes, setGuaranteeNotes] = useState('');
  const [customer, setCustomer] = useState<Customer>(); const [customerSearch, setCustomerSearch] = useState(''); const [customers, setCustomers] = useState<Customer[]>([]); const [customersLoading, setCustomersLoading] = useState(false);
  const [guarantor, setGuarantor] = useState<Guarantor>(); const [guarantorSearch, setGuarantorSearch] = useState(''); const [guarantors, setGuarantors] = useState<Guarantor[]>([]); const [guarantorsLoading, setGuarantorsLoading] = useState(false);
  const [productSearch, setProductSearch] = useState(''); const [products, setProducts] = useState<Product[]>([]); const [productsLoading, setProductsLoading] = useState(false); const [productId, setProductId] = useState(''); const [newQuantity, setNewQuantity] = useState('1'); const [newUnitPrice, setNewUnitPrice] = useState(''); const [items, setItems] = useState<DraftItem[]>([]);
  const [errors, setErrors] = useState<Record<string, string[]>>({}); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);

  useEffect(() => { const timer = setTimeout(() => { setCustomersLoading(true); getCustomers({ search: customerSearch.trim() || undefined, status: 'Active', page: 1, pageSize: 10 }, token).then(page => setCustomers(page.items)).catch(() => setCustomers([])).finally(() => setCustomersLoading(false)); }, 300); return () => clearTimeout(timer); }, [customerSearch, token]);
  useEffect(() => { const timer = setTimeout(() => { setGuarantorsLoading(true); getGuarantors({ search: guarantorSearch.trim() || undefined, isActive: true, page: 1, pageSize: 10 }, token).then(page => setGuarantors(page.items)).catch(() => setGuarantors([])).finally(() => setGuarantorsLoading(false)); }, 300); return () => clearTimeout(timer); }, [guarantorSearch, token]);
  useEffect(() => { const timer = setTimeout(() => { setProductsLoading(true); getProducts({ search: productSearch.trim() || undefined, isActive: true, page: 1, pageSize: 10 }, token).then(page => setProducts(page.items)).catch(() => setProducts([])).finally(() => setProductsLoading(false)); }, 300); return () => clearTimeout(timer); }, [productSearch, token]);

  const addItem = () => {
    const product = products.find(value => String(value.productId) === productId);
    const next: Record<string, string[]> = {};
    if (!product) next.product = ['Select a product.'];
    if (!/^\d+$/.test(newQuantity) || Number(newQuantity) < 1) next.quantity = ['Use a positive whole quantity.'];
    if (!validMoney(newUnitPrice.trim())) next.unitPrice = ['Use a nonnegative amount with at most two decimal places.'];
    if (product && items.some(item => item.product.productId === product.productId)) next.product = ['This product is already in the contract.'];
    if (Object.keys(next).length) { setErrors(old => ({ ...old, ...next })); return; }
    setItems(old => [...old, { product: product!, quantity: newQuantity, unitPrice: newUnitPrice.trim() }]); setProductId(''); setNewQuantity('1'); setNewUnitPrice(''); setErrors(old => { const copy = { ...old }; delete copy.product; delete copy.quantity; delete copy.unitPrice; delete copy.items; return copy; });
  };
  const updateItem = (index: number, field: 'quantity' | 'unitPrice', value: string) => setItems(old => old.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  const submit = async (event: FormEvent) => {
    event.preventDefault(); const next: Record<string, string[]> = {};
    if (!contractNumber.trim()) next.contractNumber = ['Contract number is required.'];
    if (!contractDate) next.contractDate = ['Contract date is required.'];
    if (!downPayment.trim()) next.downPayment = ['Down payment is required.']; else if (!validMoney(downPayment.trim())) next.downPayment = ['Use a nonnegative amount with at most two decimal places.'];
    if (!customer) next.customer = ['Select a customer.']; if (!guarantor) next.guarantor = ['Select a guarantor.']; if (!items.length) next.items = ['Add at least one product item.'];
    items.forEach((item, index) => { if (!/^\d+$/.test(item.quantity) || Number(item.quantity) < 1) next[`items[${index}].quantity`] = ['Use a positive whole quantity.']; if (!validMoney(item.unitPrice)) next[`items[${index}].unitPrice`] = ['Use a valid amount with at most two decimal places.']; });
    if (Object.keys(next).length) { setErrors(next); setMessage('Please correct the highlighted contract fields.'); return; }
    setSaving(true); setErrors({}); setMessage('');
    try { await onSubmit({ contractNumber: contractNumber.trim(), customerId: customer!.customerId, contractDate: `${contractDate}T00:00:00Z`, downPayment: Number(downPayment), items: items.map(item => ({ productId: item.product.productId, quantity: Number(item.quantity), unitPrice: Number(item.unitPrice) })), guarantorId: guarantor!.guarantorId, guarantor: null, guaranteeNotes: guaranteeNotes.trim() || null }); }
    catch (reason) { if (reason instanceof ApiError) { setErrors(reason.errors); setMessage(reason.status === 409 ? reason.message : reason.status === 400 && Object.keys(reason.errors).length ? 'Please correct the contract fields.' : reason.status === 403 ? 'You do not have permission to create contracts.' : reason.message); } else setMessage('The contract could not be created.'); }
    finally { setSaving(false); }
  };
  return <form className="contract-form" onSubmit={submit} noValidate>{message && <div className="error" role="alert"><strong>{message}</strong>{errorLines(errors).length > 0 && <ul>{errorLines(errors).map(line => <li key={line}>{line}</li>)}</ul>}</div>}
    <section className="form-section"><h2>Contract</h2><div className="form-grid"><label>Contract number<input value={contractNumber} maxLength={50} onChange={e => setContractNumber(e.target.value)} />{errors.contractNumber && <small className="field-error">{errors.contractNumber[0]}</small>}</label><label>Contract date<input type="date" value={contractDate} onChange={e => setContractDate(e.target.value)} />{errors.contractDate && <small className="field-error">{errors.contractDate[0]}</small>}</label><label>Down payment<input inputMode="decimal" value={downPayment} onChange={e => setDownPayment(e.target.value)} />{errors.downPayment && <small className="field-error">{errors.downPayment[0]}</small>}</label><label>Guarantee notes<textarea value={guaranteeNotes} onChange={e => setGuaranteeNotes(e.target.value)} /></label></div></section>
    <section className="form-section"><h2>Customer</h2>{customer ? <div className="selection"><span><strong>{customer.fullName}</strong><small>{customer.identificationNumber} · {customer.phone}</small></span><button type="button" className="secondary" onClick={() => setCustomer(undefined)}>Clear customer</button></div> : <><label>Search customers<input value={customerSearch} maxLength={150} onChange={e => setCustomerSearch(e.target.value)} /></label>{customersLoading ? <p className="lookup-state">Loading customers…</p> : <label>Customer results<select aria-label="Customer results" value="" onChange={e => setCustomer(customers.find(value => value.customerId === Number(e.target.value)))}><option value="">Select an active customer</option>{customers.map(value => <option key={value.customerId} value={value.customerId}>{value.fullName} — {value.identificationNumber}</option>)}</select></label>}</>}{errors.customer && <small className="field-error">{errors.customer[0]}</small>}</section>
    <section className="form-section"><h2>Product items</h2><div className="item-picker"><label>Search products<input value={productSearch} maxLength={150} onChange={e => setProductSearch(e.target.value)} /></label><label>Product<select aria-label="Product results" disabled={productsLoading} value={productId} onChange={e => setProductId(e.target.value)}><option value="">{productsLoading ? 'Loading products…' : 'Select an active product'}</option>{products.map(value => <option key={value.productId} value={value.productId}>{value.productCode} — {value.name}</option>)}</select></label><label>Quantity<input aria-label="New item quantity" inputMode="numeric" value={newQuantity} onChange={e => setNewQuantity(e.target.value)} /></label><label>Agreed unit price<input aria-label="New item unit price" inputMode="decimal" value={newUnitPrice} onChange={e => setNewUnitPrice(e.target.value)} /></label><button type="button" className="secondary" onClick={addItem}>Add item</button></div>{errors.product && <small className="field-error">{errors.product[0]}</small>}{errors.quantity && <small className="field-error">{errors.quantity[0]}</small>}{errors.unitPrice && <small className="field-error">{errors.unitPrice[0]}</small>}{errors.items && <small className="field-error">{errors.items[0]}</small>}
      {items.length > 0 && <div className="table-scroll selected-items"><table><thead><tr><th>Product</th><th>Reference prices</th><th>Quantity</th><th>Agreed unit price</th><th>Action</th></tr></thead><tbody>{items.map((item, index) => <tr key={item.product.productId}><td>{item.product.productCode} · {item.product.name}</td><td>Cash {formatMoney(item.product.cashPrice)}{item.product.installmentPrice === null ? '' : ` · Installment ${formatMoney(item.product.installmentPrice)}`}</td><td><input aria-label={`Quantity for ${item.product.name}`} inputMode="numeric" value={item.quantity} onChange={e => updateItem(index, 'quantity', e.target.value)} /></td><td><input aria-label={`Unit price for ${item.product.name}`} inputMode="decimal" value={item.unitPrice} onChange={e => updateItem(index, 'unitPrice', e.target.value)} /></td><td><button type="button" className="text-button" onClick={() => setItems(old => old.filter((_, itemIndex) => itemIndex !== index))}>Remove</button></td></tr>)}</tbody></table></div>}<p className="form-hint">Reference prices are informational. The agreed unit price you enter is sent to and locked by the backend; final totals and installments are calculated by the backend.</p></section>
    <section className="form-section"><h2>Guarantor</h2>{guarantor ? <div className="selection"><span><strong>{guarantor.fullName}</strong><small>{guarantor.identificationNumber} · {guarantor.phone}</small></span><button type="button" className="secondary" onClick={() => setGuarantor(undefined)}>Clear guarantor</button></div> : <><label>Search guarantors<input value={guarantorSearch} maxLength={150} onChange={e => setGuarantorSearch(e.target.value)} /></label>{guarantorsLoading ? <p className="lookup-state">Loading guarantors…</p> : <label>Guarantor results<select aria-label="Guarantor results" value="" onChange={e => setGuarantor(guarantors.find(value => value.guarantorId === Number(e.target.value)))}><option value="">Select an active guarantor</option>{guarantors.map(value => <option key={value.guarantorId} value={value.guarantorId}>{value.fullName} — {value.identificationNumber}</option>)}</select></label>}</>}{errors.guarantor && <small className="field-error">{errors.guarantor[0]}</small>}</section>
    <button className="primary" disabled={saving}>{saving ? 'Creating…' : 'Create contract'}</button>
  </form>;
}
