import { useEffect, useState, type FormEvent } from 'react';
import { ApiError } from '../api/client';
import { getContract, getContracts } from '../api/contracts';
import type { ContractDetails, ContractSummary } from '../types/contracts';
import type { CreatePaymentRequest } from '../types/payments';
import { formatMoney } from '../utils/format';

const moneyPattern = /^\d+(?:\.\d{1,2})?$/;
function validAmount(value: string) { if (!moneyPattern.test(value)) return false; const whole = value.split('.')[0].replace(/^0+(?=\d)/, ''); return Number(value) > 0 && (whole.length < 13 || whole.length === 13 && whole <= '9999999999999'); }
function backendLines(errors: Record<string, string[]>) { return Object.values(errors).flat(); }
export function PaymentForm({ token, initialContractId, onSubmit }: { token: string; initialContractId?: number; onSubmit(request: CreatePaymentRequest): Promise<void> }) {
  const [search, setSearch] = useState(''); const [contracts, setContracts] = useState<ContractSummary[]>([]); const [selected, setSelected] = useState<ContractDetails>(); const [loadingContracts, setLoadingContracts] = useState(false); const [contractError, setContractError] = useState('');
  const [reference, setReference] = useState(''); const [amount, setAmount] = useState(''); const [method, setMethod] = useState(''); const [paymentDate, setPaymentDate] = useState(''); const [notes, setNotes] = useState(''); const [errors, setErrors] = useState<Record<string, string[]>>({}); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!initialContractId) return; setLoadingContracts(true); getContract(initialContractId, token).then(value => { if (value.contract.status === 'Active') setSelected(value); else setContractError('The selected contract is not Active and cannot receive payments.'); }).catch(reason => setContractError(reason instanceof ApiError && reason.status === 404 ? 'Contract Not Found.' : 'The selected contract could not be loaded.')).finally(() => setLoadingContracts(false)); }, [initialContractId, token]);
  useEffect(() => { if (selected) return; const timer = setTimeout(() => { setLoadingContracts(true); getContracts({ search: search.trim() || undefined, status: 'Active', page: 1, pageSize: 10 }, token).then(page => setContracts(page.items)).catch(() => setContracts([])).finally(() => setLoadingContracts(false)); }, 300); return () => clearTimeout(timer); }, [search, selected, token]);
  const choose = async (contractId: number) => { if (!contractId) return; setLoadingContracts(true); setContractError(''); try { const value = await getContract(contractId, token); if (value.contract.status !== 'Active') setContractError('The selected contract is not Active and cannot receive payments.'); else setSelected(value); } catch { setContractError('The selected contract could not be loaded.'); } finally { setLoadingContracts(false); } };
  const submit = async (event: FormEvent) => {
    event.preventDefault(); if (saving) return; const next: Record<string, string[]> = {};
    if (!selected) next.contractId = ['Select an Active contract.']; if (!reference.trim()) next.paymentReference = ['Payment reference is required.']; if (!amount.trim()) next.amount = ['Amount is required.']; else if (!validAmount(amount.trim())) next.amount = ['Use a positive amount with at most two decimal places.']; if (!method.trim()) next.paymentMethod = ['Payment method is required.'];
    if (Object.keys(next).length) { setErrors(next); setMessage('Please correct the highlighted payment fields.'); return; }
    setSaving(true); setErrors({}); setMessage('');
    try { await onSubmit({ contractId: selected!.contract.contractId, paymentReference: reference.trim(), paymentDate: paymentDate ? new Date(paymentDate).toISOString() : null, amount: Number(amount), paymentMethod: method.trim(), notes: notes.trim() || null }); }
    catch (reason) {
      const apiError = reason instanceof ApiError ? reason : undefined; if (apiError?.status === 400) { setErrors(apiError.errors); setMessage(backendLines(apiError.errors)[0] || 'Please correct the payment fields.'); }
      else if (apiError?.status === 403) setMessage('Access Denied. You do not have permission to record payments.'); else if (apiError?.status === 404) setMessage('Contract Not Found. Reload and select an available Active contract.'); else if (apiError?.status === 409) setMessage(apiError.message || 'The payment conflicts with the current contract state.'); else setMessage('Unable to record the payment. Please try again.');
    } finally { setSaving(false); }
  };
  const overpayment = !!selected && validAmount(amount) && Number(amount) > selected.contract.remainingAmount;
  return <form className="contract-form payment-form" onSubmit={submit} noValidate>{message && <div className="error" role="alert">{message}</div>}
    <section className="form-section"><h2>Active contract</h2>{selected ? <><div className="selection"><span><strong>{selected.contract.contractNumber}</strong><small>{selected.contract.customerName} · Remaining {formatMoney(selected.contract.remainingAmount)}</small></span><button type="button" className="secondary" disabled={saving} onClick={() => { setSelected(undefined); setContractError(''); }}>Change contract</button></div><div className="details-grid payment-contract-summary"><div><span>Customer</span><strong>{selected.contract.customerName}</strong></div><div><span>Status</span><strong>{selected.contract.status}</strong></div><div><span>Total amount</span><strong>{formatMoney(selected.contract.totalAmount)}</strong></div><div><span>Down payment</span><strong>{formatMoney(selected.contract.downPayment)}</strong></div><div><span>Remaining amount</span><strong>{formatMoney(selected.contract.remainingAmount)}</strong></div><div><span>Contract number</span><strong>{selected.contract.contractNumber}</strong></div></div></> : <><label>Search Active contracts<input aria-label="Search Active contracts" value={search} maxLength={150} onChange={event => setSearch(event.target.value)} /></label><label>Contract results<select aria-label="Contract results" value="" disabled={loadingContracts} onChange={event => choose(Number(event.target.value))}><option value="">{loadingContracts ? 'Loading contracts…' : 'Select an Active contract'}</option>{contracts.map(contract => <option key={contract.contractId} value={contract.contractId}>{contract.contractNumber} — {contract.customerName} — remaining {formatMoney(contract.remainingAmount)}</option>)}</select></label></>}{contractError && <small className="field-error">{contractError}</small>}{errors.contractId && <small className="field-error">{errors.contractId[0]}</small>}</section>
    {selected && <section className="form-section"><h2>Current installment schedule</h2><div className="table-scroll selected-items"><table><thead><tr><th>No.</th><th>Due date</th><th>Amount</th><th>Paid</th><th>Remaining</th><th>Status</th></tr></thead><tbody>{selected.installments.map(installment => <tr key={installment.installmentId}><td>{installment.installmentNumber}</td><td>{installment.dueDate}</td><td className="numeric">{formatMoney(installment.amount)}</td><td className="numeric">{formatMoney(installment.paidAmount)}</td><td className="numeric">{formatMoney(installment.remainingAmount)}</td><td>{installment.status}</td></tr>)}</tbody></table></div></section>}
    <section className="form-section"><h2>Receipt</h2><div className="form-grid"><label>Payment reference<input value={reference} maxLength={50} onChange={event => setReference(event.target.value)} />{errors.paymentReference && <small className="field-error">{errors.paymentReference[0]}</small>}</label><label>Payment method<input value={method} maxLength={30} placeholder="Cash, Bank Transfer, Cheque…" onChange={event => setMethod(event.target.value)} />{errors.paymentMethod && <small className="field-error">{errors.paymentMethod[0]}</small>}</label><label>Amount<input inputMode="decimal" value={amount} onChange={event => setAmount(event.target.value)} />{errors.amount && <small className="field-error">{errors.amount[0]}</small>}{overpayment && <small className="field-warning">Entered amount exceeds the displayed remaining balance. The server will validate it.</small>}</label><label>Payment date <span>(optional)</span><input type="datetime-local" value={paymentDate} onChange={event => setPaymentDate(event.target.value)} /></label><label className="full-field">Notes <span>(optional)</span><textarea value={notes} onChange={event => setNotes(event.target.value)} /></label></div><p className="form-hint">Allocation will be determined by the server. No installment allocation is calculated in this form.</p></section>
    <button className="primary" disabled={saving}>{saving ? 'Recording…' : 'Record payment'}</button>
  </form>;
}
