import { useState, type FormEvent } from 'react';
import { ApiError } from '../api/client';
import type { RoleOption, CreateUserRequest, UpdateUserRequest, UserDetails } from '../types/users';

type Props = { initial?: UserDetails; roles: RoleOption[]; onSubmit(request: CreateUserRequest | UpdateUserRequest): Promise<void> };
export function UserForm({ initial, roles, onSubmit }: Props) {
  const editing=!!initial; const [username,setUsername]=useState(initial?.username??''); const [email,setEmail]=useState(initial?.email??''); const [fullName,setFullName]=useState(initial?.fullName??''); const [password,setPassword]=useState(''); const [role,setRole]=useState(initial?.role??roles[0]?.roleName??'Admin'); const [isActive,setIsActive]=useState(initial?.isActive??true); const [errors,setErrors]=useState<Record<string,string[]>>({}); const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(saving)return;const next:Record<string,string[]>={};if(!username.trim())next.username=['Username is required.'];if(!email.trim())next.email=['Email is required.'];if(!fullName.trim())next.fullName=['Full name is required.'];if(!editing&&password.length<16)next.password=['Password must be at least 16 characters.'];if(Object.keys(next).length){setErrors(next);return}setSaving(true);setErrors({});setMessage('');try{const profile={username:username.trim(),email:email.trim(),fullName:fullName.trim(),role,isActive};await onSubmit(editing?profile:{...profile,password});}catch(reason){if(reason instanceof ApiError){setErrors(reason.errors);setMessage(reason.status===400?'Please correct the highlighted fields.':reason.status===409?(reason.message.includes('username')?'A user with this username already exists.':reason.message.includes('email')?'A user with this email already exists.':reason.message.includes('administrator')||reason.message.includes('Admin role')?reason.message:'The user could not be changed because of a conflict.'):'The user could not be saved. Please try again.');}else setMessage('The user could not be saved. Please try again.');}finally{setSaving(false)}};
  return <form className="customer-form user-form" onSubmit={submit} noValidate>{message&&<div className="error" role="alert">{message}</div>}<div className="form-grid"><Field label="Username" value={username} set={setUsername} maxLength={50} error={errors.username}/><Field label="Email" type="email" value={email} set={setEmail} maxLength={100} error={errors.email}/><Field label="Full name" value={fullName} set={setFullName} maxLength={100} error={errors.fullName}/>{!editing&&<Field label="Password" type="password" value={password} set={setPassword} maxLength={1024} error={errors.password} hint="16–1024 characters. Passwords are never displayed after creation."/>}<label>Role<select aria-invalid={!!errors.role} value={role} onChange={e=>setRole(e.target.value as typeof role)}>{roles.map(item=><option key={item.roleId} value={item.roleName}>{item.roleName}</option>)}</select>{errors.role&&<small className="field-error">{errors.role[0]}</small>}</label><label className="checkbox-field user-active"><input type="checkbox" checked={isActive} onChange={e=>setIsActive(e.target.checked)}/>Active user</label></div>{editing&&initial.role==='Admin'&&(role!=='Admin'||!isActive)&&<div className="notice">At least one active Admin must remain. The server will decide whether this change is allowed.</div>}<button className="primary" disabled={saving||roles.length===0}>{saving?'Saving…':editing?'Save changes':'Create user'}</button></form>;
}
function Field({label,value,set,error,type='text',maxLength,hint}:{label:string;value:string;set(value:string):void;error?:string[];type?:string;maxLength:number;hint?:string}){return <label>{label}<input aria-label={label} aria-invalid={!!error} type={type} value={value} maxLength={maxLength} autoComplete={type==='password'?'new-password':undefined} onChange={e=>set(e.target.value)}/>{hint&&<small>{hint}</small>}{error&&<small className="field-error">{error[0]}</small>}</label>}
