-- =============================================================================
-- Installment Management System (IMS) - Database Schema
-- Database Engine: PostgreSQL 13+
-- Author: Development Team
-- Specification: docs/database/ERD.md
-- =============================================================================

-- Enable strict execution mode
SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- =============================================================================
-- 1. ROLES
-- Stores security roles for Role-Based Access Control (RBAC).
-- =============================================================================
CREATE TABLE roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT NULL
);

-- =============================================================================
-- 2. USERS
-- Stores staff credentials, authentication metadata, and assigned roles.
-- =============================================================================
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL REFERENCES roles(role_id) ON DELETE RESTRICT,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 3. CUSTOMERS
-- Manages customer identity records and contact profiles.
-- =============================================================================
CREATE TABLE customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    identification_number VARCHAR(50) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    secondary_phone VARCHAR(20) NULL,
    email VARCHAR(100) NULL,
    address TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive', 'Blacklisted')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 4. PRODUCTS
-- Reference catalog of items available for installment financing.
-- =============================================================================
CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    description TEXT NULL,
    cash_price NUMERIC(15,2) NOT NULL CHECK (cash_price >= 0.00),
    installment_price NUMERIC(15,2) NULL CHECK (installment_price IS NULL OR installment_price >= 0.00),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 5. GUARANTORS
-- Manages legal guarantors / co-signers who guarantee installment contracts.
-- =============================================================================
CREATE TABLE guarantors (
    guarantor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    identification_number VARCHAR(50) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    secondary_phone VARCHAR(20) NULL,
    address TEXT NOT NULL,
    occupation VARCHAR(100) NULL,
    workplace VARCHAR(150) NULL,
    notes TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 6. CONTRACTS
-- Core financing agreements. Constrained to fixed 12-month duration.
-- =============================================================================
CREATE TABLE contracts (
    contract_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_number VARCHAR(50) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES customers(customer_id) ON DELETE RESTRICT,
    created_by_user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    contract_date TIMESTAMPTZ NOT NULL,
    total_amount NUMERIC(15,2) NOT NULL CHECK (total_amount > 0.00),
    down_payment NUMERIC(15,2) NOT NULL CHECK (down_payment >= 0.00),
    remaining_amount NUMERIC(15,2) NOT NULL CHECK (remaining_amount >= 0.00),
    number_of_installments INTEGER NOT NULL DEFAULT 12 CHECK (number_of_installments = 12),
    status VARCHAR(20) NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft', 'Active', 'Completed', 'Voided', 'Defaulted')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_contracts_financial_amounts CHECK (down_payment <= total_amount AND remaining_amount <= total_amount)
);

-- =============================================================================
-- 7. CONTRACT_ITEMS
-- Multi-product junction entity linking products to contracts with locked pricing.
-- =============================================================================
CREATE TABLE contract_items (
    contract_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL REFERENCES contracts(contract_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(product_id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(15,2) NOT NULL CHECK (unit_price >= 0.00),
    subtotal NUMERIC(15,2) NOT NULL CHECK (subtotal >= 0.00),
    CONSTRAINT uq_contract_items_contract_product UNIQUE (contract_id, product_id)
);

-- =============================================================================
-- 8. CONTRACT_GUARANTORS
-- Junction table associating mandatory legal guarantors to contracts.
-- =============================================================================
CREATE TABLE contract_guarantors (
    contract_guarantor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL REFERENCES contracts(contract_id) ON DELETE CASCADE,
    guarantor_id BIGINT NOT NULL REFERENCES guarantors(guarantor_id) ON DELETE RESTRICT,
    notes TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_contract_guarantors_contract_guarantor UNIQUE (contract_id, guarantor_id)
);

-- =============================================================================
-- 9. INSTALLMENTS
-- Monthly payment obligations. Exactly 12 rows generated per contract schedule.
-- =============================================================================
CREATE TABLE installments (
    installment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL REFERENCES contracts(contract_id) ON DELETE CASCADE,
    installment_number INTEGER NOT NULL CHECK (installment_number BETWEEN 1 AND 12),
    due_date DATE NOT NULL,
    amount NUMERIC(15,2) NOT NULL CHECK (amount > 0.00),
    paid_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00 CHECK (paid_amount >= 0.00),
    remaining_amount NUMERIC(15,2) NOT NULL CHECK (remaining_amount >= 0.00),
    status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Paid', 'Partially Paid', 'Overdue', 'Waived')),
    CONSTRAINT uq_installments_contract_installment_number UNIQUE (contract_id, installment_number),
    CONSTRAINT chk_installments_paid_amount CHECK (paid_amount <= amount)
);

-- =============================================================================
-- 10. PAYMENTS
-- Financial cash collection transactions executed against a contract.
-- =============================================================================
CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_reference VARCHAR(50) NOT NULL UNIQUE,
    contract_id BIGINT NOT NULL REFERENCES contracts(contract_id) ON DELETE RESTRICT,
    received_by_user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    payment_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    amount NUMERIC(15,2) NOT NULL CHECK (amount > 0.00),
    payment_method VARCHAR(30) NOT NULL,
    notes TEXT NULL
);

-- =============================================================================
-- 11. PAYMENT_ALLOCATIONS
-- Maps how a single payment transaction amount is distributed across installments.
-- =============================================================================
CREATE TABLE payment_allocations (
    payment_allocation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES payments(payment_id) ON DELETE RESTRICT,
    installment_id BIGINT NOT NULL REFERENCES installments(installment_id) ON DELETE RESTRICT,
    allocated_amount NUMERIC(15,2) NOT NULL CHECK (allocated_amount > 0.00),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payment_allocations_payment_installment UNIQUE (payment_id, installment_id)
);

-- =============================================================================
-- 12. AUDIT_LOGS
-- Immutable application audit records for critical business actions.
-- No update/delete operations are exposed by the application.
-- =============================================================================
CREATE TABLE audit_logs (
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    action_type VARCHAR(50) NOT NULL,
    target_entity_type VARCHAR(50) NOT NULL,
    target_entity_id BIGINT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    previous_state VARCHAR(50) NOT NULL,
    new_state VARCHAR(50) NOT NULL,
    reference VARCHAR(100) NULL,
    note TEXT NULL,
    CONSTRAINT uq_audit_logs_action_target UNIQUE (action_type, target_entity_type, target_entity_id)
);

-- =============================================================================
-- HELPER FUNCTIONS & INTEGRITY TRIGGERS
-- =============================================================================

-- Function: Validate that payment allocation installment belongs to the same contract as the payment
CREATE OR REPLACE FUNCTION fn_validate_payment_allocation_contract()
RETURNS TRIGGER AS $$
DECLARE
    v_payment_contract_id BIGINT;
    v_installment_contract_id BIGINT;
BEGIN
    SELECT contract_id INTO v_payment_contract_id
    FROM payments
    WHERE payment_id = NEW.payment_id;

    SELECT contract_id INTO v_installment_contract_id
    FROM installments
    WHERE installment_id = NEW.installment_id;

    IF v_payment_contract_id IS NULL OR v_installment_contract_id IS NULL THEN
        RAISE EXCEPTION 'Invalid payment_id or installment_id referenced in payment allocation.';
    END IF;

    IF v_payment_contract_id <> v_installment_contract_id THEN
        RAISE EXCEPTION 'Contract mismatch: Payment contract % does not match Installment contract %.',
            v_payment_contract_id, v_installment_contract_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validate_payment_allocation_contract
BEFORE INSERT OR UPDATE ON payment_allocations
FOR EACH ROW
EXECUTE FUNCTION fn_validate_payment_allocation_contract();
