import { useEffect, useState } from 'react';
import { Link, Navigate } from 'react-router-dom';
import { ApiError } from '../api/client';
import { getDueCollections } from '../api/collections';
import { useAuth } from '../auth/AuthContext';
import { InstallmentStatusBadge } from '../components/InstallmentStatusBadge';
import { Pagination } from '../components/Pagination';
import type { CollectionPage } from '../types/collections';
import type { InstallmentStatus } from '../types/installments';
import { formatMoney } from '../utils/format';
import { canCreatePayments, canReadCollections } from '../utils/roles';

const collectionStatuses: InstallmentStatus[] = ['Pending', 'Partially Paid', 'Overdue'];
function positiveId(value: string) { return /^\d+$/.test(value) && Number(value) > 0 ? Number(value) : undefined; }
export function CollectionsPage() {
  const { token, user } = useAuth(); const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [contractId, setContractId] = useState(''); const [customerId, setCustomerId] = useState(''); const [status, setStatus] = useState<InstallmentStatus | ''>(''); const [dueFrom, setDueFrom] = useState(''); const [dueTo, setDueTo] = useState(''); const [number, setNumber] = useState(''); const [pastDueOnly, setPastDueOnly] = useState(false); const [page, setPage] = useState(1); const [data, setData] = useState<CollectionPage>(); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [retry, setRetry] = useState(0);
  useEffect(() => { const timer = setTimeout(() => { setQuery(search.trim()); setPage(1); }, 350); return () => clearTimeout(timer); }, [search]);
  useEffect(() => { if (!token || !user || !canReadCollections(user.role)) return; let current = true; setLoading(true); setError(''); getDueCollections({ search: query || undefined, contractId: positiveId(contractId), customerId: positiveId(customerId), status: status || undefined, dueFrom: dueFrom || undefined, dueTo: dueTo || undefined, installmentNumber: positiveId(number), pastDueOnly, page, pageSize: 10 }, token).then(value => { if (current) setData(value); }).catch(reason => { if (current) setError(reason instanceof ApiError && reason.status === 400 ? 'The collection filters are invalid. Check the dates and filter values.' : 'The collection queue could not be loaded. Please try again.'); }).finally(() => { if (current) setLoading(false); }); return () => { current = false; }; }, [token, user, query, contractId, customerId, status, dueFrom, dueTo, number, pastDueOnly, page, retry]);
  if (!user || !canReadCollections(user.role)) return <Navigate to="/access-denied" replace />;
  const reset = () => { setSearch(''); setQuery(''); setContractId(''); setCustomerId(''); setStatus(''); setDueFrom(''); setDueTo(''); setNumber(''); setPastDueOnly(false); setPage(1); };
  return <section><div className="page-title"><div><p className="eyebrow">Collection operations</p><h1>Collections</h1><p>Open installments selected by the server for collection attention.</p></div></div>
    <div className="panel filters collection-filters"><label>Search<input aria-label="Search collections" value={search} maxLength={150} placeholder="Contract number or customer" onChange={event => setSearch(event.target.value)} /></label><label>Contract ID<input aria-label="Collection contract ID" inputMode="numeric" value={contractId} onChange={event => { setContractId(event.target.value.replace(/\D/g, '')); setPage(1); }} /></label><label>Customer ID<input aria-label="Collection customer ID" inputMode="numeric" value={customerId} onChange={event => { setCustomerId(event.target.value.replace(/\D/g, '')); setPage(1); }} /></label><label>Status<select aria-label="Collection status" value={status} onChange={event => { setStatus(event.target.value as InstallmentStatus | ''); setPage(1); }}><option value="">All open statuses</option>{collectionStatuses.map(value => <option key={value}>{value}</option>)}</select></label><label>Number<input aria-label="Collection installment number" inputMode="numeric" value={number} onChange={event => { setNumber(event.target.value.replace(/\D/g, '').slice(0, 2)); setPage(1); }} /></label><label>Due from<input aria-label="Collection due from" type="date" value={dueFrom} onChange={event => { setDueFrom(event.target.value); setPage(1); }} /></label><label>Due to<input aria-label="Collection due to" type="date" value={dueTo} onChange={event => { setDueTo(event.target.value); setPage(1); }} /></label><label className="checkbox-field"><input aria-label="Collection past due only" type="checkbox" checked={pastDueOnly} onChange={event => { setPastDueOnly(event.target.checked); setPage(1); }} />Past due only</label><button className="secondary" onClick={reset}>Clear filters</button></div>
    {loading ? <div className="inline-state">Loading collection queue…</div> : error ? <div className="panel error-state" role="alert"><h2>Unable to load collections</h2><p>{error}</p><button className="secondary" onClick={() => setRetry(value => value + 1)}>Try again</button></div> : !data?.items.length ? <div className="panel empty-state"><h2>No installments currently require collection.</h2><p>The server returned no items for the selected collection filters.</p></div> : <div className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Installment</th><th>Contract</th><th>Customer contact</th><th>Due date</th><th>Amount</th><th>Paid</th><th>Remaining</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.items.map(item => <tr key={item.installmentId}><td><Link to={`/installments/${item.installmentId}`}>#{item.installmentNumber}</Link><small className="row-meta">ID {item.installmentId}</small></td><td><Link to={`/contracts/${item.contract.contractId}`}>{item.contract.contractNumber}</Link><small className="row-meta">{item.contract.status}</small></td><td><strong>{item.customer.fullName}</strong><small className="row-meta">{item.customer.phone}{item.customer.secondaryPhone ? ` · ${item.customer.secondaryPhone}` : ''}</small></td><td>{item.dueDate}</td><td className="numeric">{formatMoney(item.amount)}</td><td className="numeric">{formatMoney(item.paidAmount)}</td><td className="numeric"><strong>{formatMoney(item.remainingAmount)}</strong></td><td><InstallmentStatusBadge status={item.status} />{item.isPastDue ? <span className="past-due-indicator">Past due</span> : <span className="due-today-indicator">Due today</span>}</td><td><div className="actions"><Link to={`/installments/${item.installmentId}`}>View</Link>{item.contract.status === 'Active' && canCreatePayments(user.role) && <Link to={`/payments/new?contractId=${item.contract.contractId}`}>Record payment</Link>}</div></td></tr>)}</tbody></table></div><div className="as-of-note">Queue eligibility and past-due state as of {data.asOfUtcDate} (UTC), determined by the server.</div><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} onPage={setPage} /></div>}
  </section>;
}
