import { Link, Navigate, useNavigate } from 'react-router-dom';
import { createContract } from '../api/contracts';
import { useAuth } from '../auth/AuthContext';
import { ContractForm } from '../components/ContractForm';
import type { ContractRequest } from '../types/contracts';
import { canCreateContracts } from '../utils/roles';

export function ContractFormPage() {
  const { token, user } = useAuth(); const navigate = useNavigate();
  if (!user || !canCreateContracts(user.role)) return <Navigate to="/access-denied" replace />;
  const save = async (request: ContractRequest) => { const result = await createContract(request, token!); navigate(`/contracts/${result.contract.contractId}`, { replace: true, state: { notice: 'Contract created successfully.' } }); };
  return <section className="form-page contract-form-page"><div className="page-title"><div><p className="eyebrow">Contract management</p><h1>Create contract</h1><p>Create a Draft contract. Final totals and its twelve-installment schedule are generated by the backend.</p></div><Link className="button-link secondary" to="/contracts">Cancel</Link></div><div className="panel"><ContractForm token={token!} onSubmit={save} /></div></section>;
}
