import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { getInstallments } from '../api/installments';
import { useAuth } from '../auth/AuthContext';
import { InstallmentStatusBadge } from '../components/InstallmentStatusBadge';
import { Pagination } from '../components/Pagination';
import { installmentStatuses, type InstallmentPage, type InstallmentStatus } from '../types/installments';
import { formatMoney } from '../utils/format';

function positiveId(value: string) { return /^\d+$/.test(value) && Number(value) > 0 ? Number(value) : undefined; }
export function InstallmentsPage() {
  const { token } = useAuth(); const [searchParams] = useSearchParams();
  const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [contractId, setContractId] = useState(searchParams.get('contractId')?.replace(/\D/g, '') || ''); const [customerId, setCustomerId] = useState(''); const [status, setStatus] = useState<InstallmentStatus | ''>(''); const [dueFrom, setDueFrom] = useState(''); const [dueTo, setDueTo] = useState(''); const [number, setNumber] = useState(''); const [pastDueOnly, setPastDueOnly] = useState(false); const [openOnly, setOpenOnly] = useState(false); const [page, setPage] = useState(1); const [data, setData] = useState<InstallmentPage>(); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [retry, setRetry] = useState(0);
  useEffect(() => { const timer = setTimeout(() => { setQuery(search.trim()); setPage(1); }, 350); return () => clearTimeout(timer); }, [search]);
  useEffect(() => { if (!token) return; let current = true; setLoading(true); setError(''); getInstallments({ search: query || undefined, contractId: positiveId(contractId), customerId: positiveId(customerId), status: status || undefined, dueFrom: dueFrom || undefined, dueTo: dueTo || undefined, installmentNumber: positiveId(number), pastDueOnly, openOnly, page, pageSize: 10 }, token).then(value => { if (current) setData(value); }).catch(() => { if (current) setError('Installments could not be loaded. Please try again.'); }).finally(() => { if (current) setLoading(false); }); return () => { current = false; }; }, [token, query, contractId, customerId, status, dueFrom, dueTo, number, pastDueOnly, openOnly, page, retry]);
  const reset = () => { setSearch(''); setQuery(''); setContractId(''); setCustomerId(''); setStatus(''); setDueFrom(''); setDueTo(''); setNumber(''); setPastDueOnly(false); setOpenOnly(false); setPage(1); };
  return <section><div className="page-title"><div><p className="eyebrow">Installment schedule</p><h1>Installments</h1><p>Review the server-maintained balances and statuses for contract installments.</p></div></div>
    <div className="panel filters installment-filters"><label>Search<input aria-label="Search installments" value={search} maxLength={150} placeholder="Contract number or customer" onChange={event => setSearch(event.target.value)} /></label><label>Contract ID<input aria-label="Installment contract ID" inputMode="numeric" value={contractId} onChange={event => { setContractId(event.target.value.replace(/\D/g, '')); setPage(1); }} /></label><label>Customer ID<input aria-label="Installment customer ID" inputMode="numeric" value={customerId} onChange={event => { setCustomerId(event.target.value.replace(/\D/g, '')); setPage(1); }} /></label><label>Status<select aria-label="Installment status" value={status} onChange={event => { setStatus(event.target.value as InstallmentStatus | ''); setPage(1); }}><option value="">All statuses</option>{installmentStatuses.map(value => <option key={value}>{value}</option>)}</select></label><label>Number<input aria-label="Installment number" inputMode="numeric" value={number} onChange={event => { setNumber(event.target.value.replace(/\D/g, '').slice(0, 2)); setPage(1); }} /></label><label>Due from<input aria-label="Due from" type="date" value={dueFrom} onChange={event => { setDueFrom(event.target.value); setPage(1); }} /></label><label>Due to<input aria-label="Due to" type="date" value={dueTo} onChange={event => { setDueTo(event.target.value); setPage(1); }} /></label><label className="checkbox-field"><input aria-label="Past due only" type="checkbox" checked={pastDueOnly} onChange={event => { setPastDueOnly(event.target.checked); setPage(1); }} />Past due only</label><label className="checkbox-field"><input aria-label="Open only" type="checkbox" checked={openOnly} onChange={event => { setOpenOnly(event.target.checked); setPage(1); }} />Open only</label><button className="secondary" onClick={reset}>Clear filters</button></div>
    {loading ? <div className="inline-state">Loading installments…</div> : error ? <div className="panel error-state" role="alert"><h2>Unable to load installments</h2><p>{error}</p><button className="secondary" onClick={() => setRetry(value => value + 1)}>Try again</button></div> : !data?.items.length ? <div className="panel empty-state"><h2>No installments found</h2><p>Try changing the supported schedule filters.</p></div> : <div className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>ID</th><th>Contract</th><th>Customer</th><th>No.</th><th>Due date</th><th>Amount</th><th>Paid</th><th>Remaining</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.items.map(item => <tr key={item.installmentId}><td>{item.installmentId}</td><td><Link to={`/contracts/${item.contract.contractId}`}>{item.contract.contractNumber}</Link></td><td>{item.customer.fullName}</td><td>{item.installmentNumber}</td><td>{item.dueDate}</td><td className="numeric">{formatMoney(item.amount)}</td><td className="numeric">{formatMoney(item.paidAmount)}</td><td className="numeric">{formatMoney(item.remainingAmount)}</td><td><InstallmentStatusBadge status={item.status} />{item.isPastDue && <span className="past-due-indicator">Past due</span>}</td><td><Link to={`/installments/${item.installmentId}`}>View</Link></td></tr>)}</tbody></table></div><div className="as-of-note">Balances as of {data.asOfUtcDate} (UTC)</div><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} onPage={setPage} /></div>}
  </section>;
}
