import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { App } from '../App';
const admin = { id: 1, email: 'admin@example.com', role: 'Admin' };
function response(body: unknown, status = 200) { return Promise.resolve(new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } })); }
function go(path: string) { history.pushState({}, '', path); render(<App />); }
async function login() { go('/login'); fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'admin@example.com' } }); fireEvent.change(screen.getByLabelText('Password'), { target: { value: 'secret-password' } }); fireEvent.click(screen.getByRole('button', { name: 'Sign in' })); await screen.findByRole('button', { name: 'Log out' }); }
describe('IMS authentication', () => {
  it('logs in successfully and reaches the dashboard', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementationOnce(() => response({ token: 'jwt', expiresAtUtc: '2030-01-01T00:00:00Z', user: admin })).mockImplementation(() => response({ totalCustomers: 2, totalContracts: 1, totalPaymentsReceived: 50, openInstallmentCount: 3, openInstallmentBalance: 25, asOfUtcDate: '2026-09-17' })); await login(); expect(fetchMock).toHaveBeenCalled(); expect(sessionStorage.getItem('ims.auth.token')).toBe('jwt'); });
  it('shows safe invalid-credentials feedback', async () => { vi.spyOn(globalThis, 'fetch').mockImplementation(() => response({ message: 'Invalid email or password.' }, 401)); go('/login'); fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'bad@example.com' } }); fireEvent.change(screen.getByLabelText('Password'), { target: { value: 'bad-password' } }); fireEvent.click(screen.getByRole('button', { name: 'Sign in' })); expect(await screen.findByRole('alert')).toHaveTextContent('Invalid email or password.'); });
  it('redirects an unauthenticated protected route', async () => { go('/dashboard'); expect(await screen.findByRole('heading', { name: 'Welcome back' })).toBeInTheDocument(); });
  it('restores a stored session through auth/me', async () => { sessionStorage.setItem('ims.auth.token', 'jwt'); const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation((input) => String(input).endsWith('/api/auth/me') ? response(admin) : response({ totalCustomers: 0, totalContracts: 0, totalPaymentsReceived: 0, openInstallmentCount: 0, openInstallmentBalance: 0, asOfUtcDate: '2026-09-17' })); go('/dashboard'); expect(await screen.findByText(/Welcome, admin@example.com/)).toBeInTheDocument(); expect(fetchMock.mock.calls[0][0]).toContain('/api/auth/me'); });
  it('clears an invalid stored session', async () => { sessionStorage.setItem('ims.auth.token', 'expired'); vi.spyOn(globalThis, 'fetch').mockImplementation(() => response({}, 401)); go('/dashboard'); expect(await screen.findByRole('heading', { name: 'Welcome back' })).toBeInTheDocument(); expect(sessionStorage.getItem('ims.auth.token')).toBeNull(); });
  it('logs out and clears the session', async () => { vi.spyOn(globalThis, 'fetch').mockImplementationOnce(() => response({ token: 'jwt', expiresAtUtc: '2030-01-01T00:00:00Z', user: admin })).mockImplementation(() => response({ totalCustomers: 0, totalContracts: 0, totalPaymentsReceived: 0, openInstallmentCount: 0, openInstallmentBalance: 0, asOfUtcDate: '2026-09-17' })); await login(); fireEvent.click(screen.getByRole('button', { name: 'Log out' })); expect(await screen.findByRole('heading', { name: 'Welcome back' })).toBeInTheDocument(); expect(sessionStorage.getItem('ims.auth.token')).toBeNull(); });
  it('shows role-aware navigation', async () => { sessionStorage.setItem('ims.auth.token', 'jwt'); vi.spyOn(globalThis, 'fetch').mockImplementation(() => response({ ...admin, role: 'Sales Agent' })); go('/dashboard'); await screen.findByText(/Welcome, admin@example.com/); expect(screen.queryByRole('link', { name: 'Users' })).not.toBeInTheDocument(); expect(screen.queryByRole('link', { name: 'Reports' })).not.toBeInTheDocument(); expect(screen.getByRole('link', { name: 'Customers' })).toBeInTheDocument(); });
  it('renders the access denied route', async () => { sessionStorage.setItem('ims.auth.token', 'jwt'); vi.spyOn(globalThis, 'fetch').mockImplementation(() => response(admin)); go('/access-denied'); expect(await screen.findByRole('heading', { name: 'Access denied' })).toBeInTheDocument(); });
  it('handles a forbidden summary without exposing details', async () => { sessionStorage.setItem('ims.auth.token', 'jwt'); vi.spyOn(globalThis, 'fetch').mockImplementation((input) => String(input).endsWith('/api/auth/me') ? response(admin) : response({ detail: 'internal' }, 403)); go('/dashboard'); expect(await screen.findByText('Dashboard metrics are not available for your account.')).toBeInTheDocument(); });
});
