import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { App } from '../App';
import type { Role } from '../types/api';

const item = { installmentId: 31, installmentNumber: 2, dueDate: '2026-09-10', amount: 100, paidAmount: 40, remainingAmount: 60, status: 'Partially Paid', isPastDue: true, isOpen: true, contract: { contractId: 44, contractNumber: 'CNT-044', status: 'Active' }, customer: { customerId: 7, fullName: 'Layla Hassan', phone: '07701234567', secondaryPhone: '07801234567' } };
const page = { items: [item], totalCount: 1, page: 1, pageSize: 10, asOfUtcDate: '2026-09-19' };
const json = (body: unknown, status = 200) => Promise.resolve(new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }));
function open(path: string, role: Role = 'Admin', handler: (url: string, init?: RequestInit) => Promise<Response> = () => json(page)) { sessionStorage.setItem('ims.auth.token', 'jwt'); vi.spyOn(globalThis, 'fetch').mockImplementation((input, init) => { const url = String(input); return url.endsWith('/api/auth/me') ? json({ id: 1, email: 'user@example.com', role }) : handler(url, init); }); history.pushState({}, '', path); render(<App />); }

describe('Collections module', () => {
  it.each<Role>(['Admin', 'Financial Manager', 'Collection Officer'])('%s can open Collections', async role => { open('/collections', role); expect(await screen.findByText('Layla Hassan')).toBeInTheDocument(); expect(screen.getByRole('link', { name: 'Collections' })).toBeInTheDocument(); });
  it.each<Role>(['Sales Agent', 'Auditor'])('%s is denied and has no Collections navigation', async role => { open('/collections', role); expect(await screen.findByRole('heading', { name: 'Access denied' })).toBeInTheDocument(); expect(screen.queryByRole('link', { name: 'Collections' })).not.toBeInTheDocument(); });
  it('uses the exact due collections endpoint', async () => { let requested = ''; open('/collections', 'Admin', url => { requested = url; return json(page); }); await screen.findByText('Layla Hassan'); expect(requested).toContain('/api/collections/due?'); });
  it('renders actual queue, contact, amounts, status, and backend metadata', async () => { open('/collections'); await screen.findByText('Layla Hassan'); expect(screen.getByText('07701234567 · 07801234567')).toBeInTheDocument(); expect(screen.getByText('2026-09-10')).toBeInTheDocument(); expect(screen.getByText('100.00')).toBeInTheDocument(); expect(screen.getByText('40.00')).toBeInTheDocument(); expect(screen.getByText('60.00')).toBeInTheDocument(); expect(screen.getAllByText('Partially Paid').length).toBeGreaterThan(1); expect(screen.getByText('Past due')).toBeInTheDocument(); expect(screen.getByText(/2026-09-19 \(UTC\), determined by the server/)).toBeInTheDocument(); });
  it('uses server pagination', async () => { let requestedPage = 1; open('/collections', 'Admin', url => { requestedPage = Number(new URL(url).searchParams.get('page')); return json({ ...page, totalCount: 21, page: requestedPage }); }); await screen.findByText(/Page 1 of 3/); fireEvent.click(screen.getByRole('button', { name: 'Next' })); await waitFor(() => expect(requestedPage).toBe(2)); });
  it('sends only supported queue filters', async () => { const urls: string[] = []; open('/collections', 'Admin', url => { urls.push(url); return json({ ...page, items: [] }); }); await screen.findByText('No installments currently require collection.'); fireEvent.change(screen.getByLabelText('Search collections'), { target: { value: 'Layla' } }); fireEvent.change(screen.getByLabelText('Collection contract ID'), { target: { value: '44' } }); fireEvent.change(screen.getByLabelText('Collection customer ID'), { target: { value: '7' } }); fireEvent.change(screen.getByLabelText('Collection status'), { target: { value: 'Partially Paid' } }); fireEvent.change(screen.getByLabelText('Collection installment number'), { target: { value: '2' } }); fireEvent.change(screen.getByLabelText('Collection due from'), { target: { value: '2026-09-01' } }); fireEvent.change(screen.getByLabelText('Collection due to'), { target: { value: '2026-09-30' } }); fireEvent.click(screen.getByLabelText('Collection past due only')); await waitFor(() => expect(urls.some(url => url.includes('search=Layla') && url.includes('contractId=44') && url.includes('customerId=7') && url.includes('status=Partially+Paid') && url.includes('installmentNumber=2') && url.includes('dueFrom=2026-09-01') && url.includes('dueTo=2026-09-30') && url.includes('pastDueOnly=true'))).toBe(true), { timeout: 1500 }); });
  it('clears filters', async () => { const urls: string[] = []; open('/collections', 'Admin', url => { urls.push(url); return json({ ...page, items: [] }); }); await screen.findByText('No installments currently require collection.'); fireEvent.change(screen.getByLabelText('Collection contract ID'), { target: { value: '44' } }); fireEvent.click(screen.getByRole('button', { name: 'Clear filters' })); await waitFor(() => expect(urls.at(-1)).not.toContain('contractId=')); });
  it('shows empty queue wording', async () => { open('/collections', 'Admin', () => json({ ...page, items: [], totalCount: 0 })); expect(await screen.findByText('No installments currently require collection.')).toBeInTheDocument(); });
  it('shows safe filter validation and server errors', async () => { open('/collections', 'Admin', () => json({ detail: 'SQL stack trace' }, 400)); expect(await screen.findByRole('alert')).toHaveTextContent('collection filters are invalid'); expect(screen.queryByText(/SQL stack/)).not.toBeInTheDocument(); });
  it('shows a generic safe infrastructure error and retry', async () => { open('/collections', 'Admin', () => json({ detail: 'database internals' }, 500)); expect(await screen.findByRole('alert')).toHaveTextContent('collection queue could not be loaded'); expect(screen.queryByText('database internals')).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Try again' })).toBeInTheDocument(); });
  it('links to contract and installment details', async () => { open('/collections'); await screen.findByText('Layla Hassan'); expect(screen.getByRole('link', { name: 'CNT-044' })).toHaveAttribute('href', '/contracts/44'); expect(screen.getByRole('link', { name: '#2' })).toHaveAttribute('href', '/installments/31'); });
  it.each<Role>(['Admin', 'Financial Manager', 'Collection Officer'])('%s sees contract-only Record payment navigation', async role => { open('/collections', role); const link = await screen.findByRole('link', { name: 'Record payment' }); expect(link).toHaveAttribute('href', '/payments/new?contractId=44'); expect(link.getAttribute('href')).not.toContain('installmentId'); });
  it('hides payment navigation unless the returned contract is Active', async () => { open('/collections', 'Admin', () => json({ ...page, items: [{ ...item, contract: { ...item.contract, status: 'Completed' } }] })); await screen.findByText('Layla Hassan'); expect(screen.queryByRole('link', { name: 'Record payment' })).not.toBeInTheDocument(); });
  it('renders backend queue membership without calculating eligibility', async () => { open('/collections', 'Admin', () => json({ ...page, items: [{ ...item, dueDate: '2099-12-31', isPastDue: false }] })); expect(await screen.findByText('2099-12-31')).toBeInTheDocument(); expect(screen.queryByText('Past due')).not.toBeInTheDocument(); });
  it('is read-only and has no mutation or allocation controls', async () => { open('/collections'); await screen.findByText('Layla Hassan'); for (const name of [/edit/i, /delete/i, /mark paid/i, /mark overdue/i, /waive/i, /change status/i, /change due date/i, /manual allocation/i]) { expect(screen.queryByRole('button', { name })).not.toBeInTheDocument(); expect(screen.queryByRole('link', { name })).not.toBeInTheDocument(); } });
});
