import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { App } from '../App';
import type { Role } from '../types/api';

const summary = { contractId: 44, contractNumber: 'CNT-044', customerId: 7, customerName: 'Layla Hassan', createdByUserId: 1, contractDate: '2026-09-18T00:00:00Z', totalAmount: 240, downPayment: 24, remainingAmount: 216, numberOfInstallments: 12, status: 'Draft', createdAt: '2026-09-18T10:00:00Z' } as const;
const customer = { customerId: 7, fullName: 'Layla Hassan', identificationNumber: 'IQ-77', phone: '07701234567', secondaryPhone: null, email: null, address: 'Baghdad', status: 'Active', createdAt: '2026-01-01T00:00:00Z' };
const product = { productId: 12, productCode: 'REF-001', name: 'Refrigerator', description: null, cashPrice: 100, installmentPrice: 120, isActive: true, createdAt: '2026-01-01T00:00:00Z' };
const guarantor = { guarantorId: 9, fullName: 'Omar Ali', identificationNumber: 'G-9', phone: '07800000000', secondaryPhone: null, address: 'Baghdad', occupation: 'Engineer', workplace: 'Office', notes: null, isActive: true, createdAt: '2026-01-01T00:00:00Z' };
const details = { contract: summary, items: [{ contractItemId: 1, productId: 12, productCode: 'REF-001', productName: 'Refrigerator', quantity: 2, unitPrice: 120, subtotal: 240 }], guarantors: [{ ...guarantor, guaranteeNotes: 'Guarantee note' }], installments: Array.from({ length: 12 }, (_, index) => ({ installmentId: index + 1, installmentNumber: index + 1, dueDate: `2026-${String(index + 1).padStart(2, '0')}-18`, amount: 18, paidAmount: 0, remainingAmount: 18, status: 'Pending' })) };
const json = (body: unknown, status = 200) => Promise.resolve(new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }));
function defaultHandler(url: string, _init?: RequestInit) { if (url.includes('/api/customers')) return json({ items: [customer], totalCount: 1, page: 1, pageSize: 10 }); if (url.includes('/api/products')) return json({ items: [product], totalCount: 1, page: 1, pageSize: 10 }); if (url.includes('/api/guarantors')) return json({ items: [guarantor], totalCount: 1, page: 1, pageSize: 10 }); return json({ items: [summary], totalCount: 1, page: 1, pageSize: 10 }); }
function open(path: string, role: Role = 'Admin', handler: (url: string, init?: RequestInit) => Promise<Response> = defaultHandler) { sessionStorage.setItem('ims.auth.token', 'jwt'); vi.spyOn(globalThis, 'fetch').mockImplementation((input, init) => { const url = String(input); if (url.endsWith('/api/auth/me')) return json({ id: 1, email: 'user@example.com', role }); return handler(url, init); }); history.pushState({}, '', path); render(<App />); }
async function populateForm() {
  await screen.findByRole('heading', { name: 'Create contract' });
  fireEvent.change(screen.getByLabelText('Contract number'), { target: { value: 'CNT-NEW' } }); fireEvent.change(screen.getByLabelText('Contract date'), { target: { value: '2026-09-20' } }); fireEvent.change(screen.getByLabelText('Down payment'), { target: { value: '10.00' } });
  await screen.findByRole('option', { name: /Layla Hassan/ }); fireEvent.change(screen.getByLabelText('Customer results'), { target: { value: '7' } });
  await screen.findByRole('option', { name: /REF-001/ }); fireEvent.change(screen.getByLabelText('Product results'), { target: { value: '12' } }); fireEvent.change(screen.getByLabelText('New item quantity'), { target: { value: '2' } }); fireEvent.change(screen.getByLabelText('New item unit price'), { target: { value: '120.00' } }); fireEvent.click(screen.getByRole('button', { name: 'Add item' }));
  await screen.findByRole('option', { name: /Omar Ali/ }); fireEvent.change(screen.getByLabelText('Guarantor results'), { target: { value: '9' } });
}

describe('Contracts module', () => {
  it('loads and renders contract rows and finances', async () => { open('/contracts'); expect(await screen.findByText('CNT-044')).toBeInTheDocument(); expect(screen.getByText('Layla Hassan')).toBeInTheDocument(); expect(screen.getByText('240.00')).toBeInTheDocument(); expect(screen.getAllByText('Draft')).toHaveLength(2); });
  it('uses server pagination', async () => { let page = 1; open('/contracts', 'Admin', url => { page = Number(new URL(url).searchParams.get('page')); return json({ items: [summary], totalCount: 21, page, pageSize: 10 }); }); await screen.findByText(/Page 1 of 3/); fireEvent.click(screen.getByRole('button', { name: 'Next' })); await waitFor(() => expect(page).toBe(2)); });
  it('sends debounced search and exact status and resets page', async () => { const urls: string[] = []; open('/contracts', 'Admin', url => { urls.push(url); return json({ items: [], totalCount: 0, page: 1, pageSize: 10 }); }); await screen.findByText('No contracts found'); fireEvent.change(screen.getByLabelText('Search contracts'), { target: { value: 'Layla' } }); fireEvent.change(screen.getByLabelText('Contract status'), { target: { value: 'Defaulted' } }); await waitFor(() => expect(urls.some(url => url.includes('search=Layla') && url.includes('status=Defaulted') && url.includes('page=1'))).toBe(true), { timeout: 1200 }); });
  it('clears list filters', async () => { const urls: string[] = []; open('/contracts', 'Admin', url => { urls.push(url); return json({ items: [], totalCount: 0, page: 1, pageSize: 10 }); }); await screen.findByText('No contracts found'); fireEvent.change(screen.getByLabelText('Contract status'), { target: { value: 'Active' } }); fireEvent.click(screen.getByRole('button', { name: 'Clear filters' })); await waitFor(() => expect(urls.at(-1)).not.toContain('status=')); });
  it('renders empty and safe error states', async () => { open('/contracts', 'Admin', () => json({ detail: 'database trace' }, 500)); expect(await screen.findByRole('alert')).toHaveTextContent('Contracts could not be loaded'); expect(screen.queryByText('database trace')).not.toBeInTheDocument(); });
  it.each<Role>(['Admin', 'Financial Manager', 'Sales Agent'])('%s can create contracts', async role => { open('/contracts', role); expect(await screen.findByRole('link', { name: 'Create contract' })).toBeInTheDocument(); });
  it.each<Role>(['Collection Officer', 'Auditor'])('%s is read-only', async role => { open('/contracts', role); await screen.findByText('CNT-044'); expect(screen.queryByRole('link', { name: 'Create contract' })).not.toBeInTheDocument(); });
  it.each<Role>(['Collection Officer', 'Auditor'])('guards create route from %s', async role => { open('/contracts/new', role); expect(await screen.findByRole('heading', { name: 'Access denied' })).toBeInTheDocument(); });
  it('renders contract details, customer, items, guarantor, schedule, status and finances', async () => { open('/contracts/44', 'Admin', () => json(details)); expect(await screen.findByRole('heading', { name: 'CNT-044' })).toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'Customer' })).toBeInTheDocument(); expect(screen.getByText('Refrigerator')).toBeInTheDocument(); expect(screen.getByText('Omar Ali')).toBeInTheDocument(); expect(screen.getByText('Guarantee note')).toBeInTheDocument(); expect(screen.getAllByText('Pending')).toHaveLength(12); expect(screen.getByText('216.00')).toBeInTheDocument(); expect(screen.getByText('Draft')).toBeInTheDocument(); });
  it('shows Contract Not Found', async () => { open('/contracts/999', 'Admin', () => json({}, 404)); expect(await screen.findByRole('heading', { name: 'Contract Not Found' })).toBeInTheDocument(); });
  it('loads searchable active selector requests', async () => { const urls: string[] = []; open('/contracts/new', 'Admin', (url, init) => { urls.push(url); return defaultHandler(url, init); }); await screen.findByRole('heading', { name: 'Create contract' }); await screen.findByRole('option', { name: /Layla Hassan/ }); expect(urls.some(url => url.includes('/api/customers?') && url.includes('status=Active') && url.includes('pageSize=10'))).toBe(true); expect(urls.some(url => url.includes('/api/products?') && url.includes('isActive=true'))).toBe(true); expect(urls.some(url => url.includes('/api/guarantors?') && url.includes('isActive=true'))).toBe(true); });
  it('selects and clears customer and guarantor', async () => { open('/contracts/new'); await screen.findByRole('option', { name: /Layla Hassan/ }); fireEvent.change(screen.getByLabelText('Customer results'), { target: { value: '7' } }); expect(screen.getByRole('button', { name: 'Clear customer' })).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Clear customer' })); expect(screen.getByLabelText('Customer results')).toBeInTheDocument(); await screen.findByRole('option', { name: /Omar Ali/ }); fireEvent.change(screen.getByLabelText('Guarantor results'), { target: { value: '9' } }); expect(screen.getByRole('button', { name: 'Clear guarantor' })).toBeInTheDocument(); });
  it('adds, updates and removes product items', async () => { open('/contracts/new'); await screen.findByRole('option', { name: /REF-001/ }); fireEvent.change(screen.getByLabelText('Product results'), { target: { value: '12' } }); fireEvent.change(screen.getByLabelText('New item unit price'), { target: { value: '120.00' } }); fireEvent.click(screen.getByRole('button', { name: 'Add item' })); expect(screen.getByLabelText('Quantity for Refrigerator')).toHaveValue('1'); fireEvent.change(screen.getByLabelText('Quantity for Refrigerator'), { target: { value: '3' } }); expect(screen.getByLabelText('Quantity for Refrigerator')).toHaveValue('3'); fireEvent.click(screen.getByRole('button', { name: 'Remove' })); expect(screen.queryByLabelText('Quantity for Refrigerator')).not.toBeInTheDocument(); });
  it('validates required fields, down payment precision and no items', async () => { open('/contracts/new'); await screen.findByRole('heading', { name: 'Create contract' }); fireEvent.change(screen.getByLabelText('Down payment'), { target: { value: '1.234' } }); fireEvent.click(screen.getByRole('button', { name: 'Create contract' })); expect(await screen.findByText('Contract number is required.')).toBeInTheDocument(); expect(screen.getAllByText(/Add at least one product item/).length).toBeGreaterThan(0); expect(screen.getAllByText(/at most two decimal places/).length).toBeGreaterThan(0); });
  it('submits exact create fields, date, quantity and no status mutation, while disabled', async () => { let sent: Record<string, unknown> | undefined; let resolvePost!: (value: Response) => void; open('/contracts/new', 'Sales Agent', (url, init) => { if (init?.method === 'POST') return new Promise(resolve => { sent = JSON.parse(String(init.body)); resolvePost = resolve; }); if (url.endsWith('/api/contracts/44')) return json(details); return defaultHandler(url, init); }); await populateForm(); fireEvent.click(screen.getByRole('button', { name: 'Create contract' })); expect(screen.getByRole('button', { name: 'Creating…' })).toBeDisabled(); expect(sent).toMatchObject({ contractNumber: 'CNT-NEW', customerId: 7, contractDate: '2026-09-20T00:00:00Z', downPayment: 10, guarantorId: 9, items: [{ productId: 12, quantity: 2, unitPrice: 120 }] }); expect(sent).not.toHaveProperty('status'); resolvePost(await json(details, 201)); expect(await screen.findByRole('status')).toHaveTextContent('created successfully'); });
  it('shows conflict and backend business validation safely', async () => { open('/contracts/new', 'Admin', (url, init) => init?.method === 'POST' ? json({ detail: 'Customer must be active.' }, 409) : defaultHandler(url, init)); await populateForm(); fireEvent.click(screen.getByRole('button', { name: 'Create contract' })); expect(await screen.findByRole('alert')).toHaveTextContent('Customer must be active.'); });
  it('maps backend field validation without exposing unrelated data', async () => { open('/contracts/new', 'Admin', (url, init) => init?.method === 'POST' ? json({ errors: { DownPayment: ['Backend financed principal validation.'] }, trace: 'secret' }, 400) : defaultHandler(url, init)); await populateForm(); fireEvent.click(screen.getByRole('button', { name: 'Create contract' })); expect(await screen.findByRole('alert')).toHaveTextContent('Backend financed principal validation.'); expect(screen.queryByText('secret')).not.toBeInTheDocument(); });
  it.each<Role>(['Admin', 'Financial Manager'])('%s sees activation for a Draft contract', async role => { open('/contracts/44', role, () => json(details)); expect(await screen.findByRole('button', { name: 'Activate contract' })).toBeInTheDocument(); });
  it.each<Role>(['Sales Agent', 'Collection Officer', 'Auditor'])('%s cannot see activation for a Draft contract', async role => { open('/contracts/44', role, () => json(details)); await screen.findByRole('heading', { name: 'CNT-044' }); expect(screen.queryByRole('button', { name: 'Activate contract' })).not.toBeInTheDocument(); });
  it.each(['Active', 'Completed', 'Voided', 'Defaulted'] as const)('does not show activation for %s contracts', async status => { open('/contracts/44', 'Admin', () => json({ ...details, contract: { ...summary, status } })); await screen.findByRole('heading', { name: 'CNT-044' }); expect(screen.queryByRole('button', { name: 'Activate contract' })).not.toBeInTheDocument(); });
  it('opens activation summary and requires confirmation', async () => { open('/contracts/44', 'Admin', () => json(details)); fireEvent.click(await screen.findByRole('button', { name: 'Activate contract' })); expect(screen.getByRole('dialog')).toHaveTextContent('does not create a payment transaction'); expect(screen.getByRole('dialog')).toHaveTextContent('CNT-044'); expect(screen.getByRole('button', { name: 'Activate contract' })).toBeDisabled(); });
  it('limits reference and sends only allowed activation fields while pending', async () => { let sent: Record<string, unknown> | undefined; let resolvePost!: (value: Response) => void; open('/contracts/44', 'Admin', (_url, init) => init?.method === 'POST' ? new Promise(resolve => { sent = JSON.parse(String(init.body)); resolvePost = resolve; }) : json(details)); fireEvent.click(await screen.findByRole('button', { name: 'Activate contract' })); fireEvent.click(screen.getByLabelText('I confirm that the agreed down payment has been received.')); fireEvent.change(screen.getByLabelText(/Reference/), { target: { value: 'R'.repeat(110) } }); fireEvent.change(screen.getByLabelText(/Note/), { target: { value: 'Received at branch' } }); fireEvent.click(screen.getByRole('button', { name: 'Activate contract' })); expect(screen.getByRole('button', { name: 'Activating…' })).toBeDisabled(); expect((screen.getByLabelText(/Reference/) as HTMLInputElement).value).toHaveLength(100); expect(sent).toEqual({ downPaymentConfirmed: true, reference: 'R'.repeat(100), note: 'Received at branch' }); resolvePost(await json({ ...details, contract: { ...summary, status: 'Active' } })); expect(await screen.findByRole('status')).toHaveTextContent('activated successfully'); });
  it('refetches after success, displays Active, and removes activation', async () => { let active = false; open('/contracts/44', 'Admin', (_url, init) => { if (init?.method === 'POST') { active = true; return json({ ...details, contract: { ...summary, status: 'Active' } }); } return json(active ? { ...details, contract: { ...summary, status: 'Active' } } : details); }); fireEvent.click(await screen.findByRole('button', { name: 'Activate contract' })); fireEvent.click(screen.getByLabelText('I confirm that the agreed down payment has been received.')); fireEvent.click(screen.getByRole('button', { name: 'Activate contract' })); expect(await screen.findByRole('status')).toHaveTextContent('activated successfully'); expect(screen.getAllByText('Active').length).toBeGreaterThan(0); expect(screen.queryByRole('button', { name: 'Activate contract' })).not.toBeInTheDocument(); });
  it.each([[400, { errors: { DownPaymentConfirmed: ['Confirmation is required.'] } }, 'Confirmation is required.'], [403, {}, 'Access Denied'], [404, {}, 'Contract Not Found'], [500, { detail: 'raw server trace' }, 'Unable to activate the contract']] as const)('handles activation error %s safely', async (status, body, message) => { open('/contracts/44', 'Admin', (_url, init) => init?.method === 'POST' ? json(body, status) : json(details)); fireEvent.click(await screen.findByRole('button', { name: 'Activate contract' })); fireEvent.click(screen.getByLabelText('I confirm that the agreed down payment has been received.')); fireEvent.click(screen.getByRole('button', { name: 'Activate contract' })); expect(await screen.findByRole('alert')).toHaveTextContent(message); expect(screen.queryByText('raw server trace')).not.toBeInTheDocument(); });
  it.each(['Contract is already active.', 'The installment schedule has an integrity conflict.'])('shows 409 business conflict: %s', async message => { open('/contracts/44', 'Admin', (_url, init) => init?.method === 'POST' ? json({ detail: message }, 409) : json(details)); fireEvent.click(await screen.findByRole('button', { name: 'Activate contract' })); fireEvent.click(screen.getByLabelText('I confirm that the agreed down payment has been received.')); fireEvent.click(screen.getByRole('button', { name: 'Activate contract' })); expect(await screen.findByRole('alert')).toHaveTextContent(message); });
  it('refetches on 409 and closes activation when another user activated first', async () => { let gets = 0; open('/contracts/44', 'Admin', (_url, init) => { if (init?.method === 'POST') return json({ detail: 'Contract is already active.' }, 409); gets++; return json(gets > 1 ? { ...details, contract: { ...summary, status: 'Active' } } : details); }); fireEvent.click(await screen.findByRole('button', { name: 'Activate contract' })); fireEvent.click(screen.getByLabelText('I confirm that the agreed down payment has been received.')); fireEvent.click(screen.getByRole('button', { name: 'Activate contract' })); expect(await screen.findByRole('alert')).toHaveTextContent('already active'); await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument()); expect(screen.getAllByText('Active').length).toBeGreaterThan(0); expect(screen.queryByRole('button', { name: 'Activate contract' })).not.toBeInTheDocument(); });
  it('uses a null optional reference and note', async () => { let sent: Record<string, unknown> | undefined; open('/contracts/44', 'Admin', (_url, init) => { if (init?.method === 'POST') { sent = JSON.parse(String(init.body)); return json({ ...details, contract: { ...summary, status: 'Active' } }); } return json({ ...details, contract: { ...summary, status: sent ? 'Active' : 'Draft' } }); }); fireEvent.click(await screen.findByRole('button', { name: 'Activate contract' })); fireEvent.click(screen.getByLabelText('I confirm that the agreed down payment has been received.')); fireEvent.click(screen.getByRole('button', { name: 'Activate contract' })); await screen.findByRole('status'); expect(sent).toEqual({ downPaymentConfirmed: true, reference: null, note: null }); });
  it('contains no unrelated lifecycle or edit controls', async () => { open('/contracts/44', 'Admin', () => json(details)); await screen.findByRole('heading', { name: 'CNT-044' }); expect(screen.queryByRole('button', { name: /void|default|complete|payment|change status/i })).not.toBeInTheDocument(); expect(screen.queryByRole('link', { name: /edit contract/i })).not.toBeInTheDocument(); });
  it('does not register a contract edit route', async () => { open('/contracts/44/edit'); expect(await screen.findByRole('heading', { name: 'Page not found' })).toBeInTheDocument(); });
});
