import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { App } from '../App';
import type { Role } from '../types/api';
const customer = { customerId: 7, fullName: 'Layla Hassan', identificationNumber: 'IQ-77', phone: '07701234567', secondaryPhone: null, email: 'layla@example.com', address: 'Baghdad', status: 'Active', createdAt: '2026-09-17T10:00:00Z' };
const json = (body: unknown, status = 200) => Promise.resolve(new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }));
function open(path: string, role: Role = 'Admin', handler?: (url: string, init?: RequestInit) => Promise<Response>) { sessionStorage.setItem('ims.auth.token', 'jwt'); vi.spyOn(globalThis, 'fetch').mockImplementation((input, init) => { const url = String(input); if (url.endsWith('/api/auth/me')) return json({ id: 1, email: 'user@example.com', role }); return handler ? handler(url, init) : json({ items: [customer], totalCount: 1, page: 1, pageSize: 10 }); }); history.pushState({}, '', path); render(<App />); }
describe('Customers module', () => {
  it('loads rows for an authenticated user', async () => { open('/customers'); expect(await screen.findByText('Layla Hassan')).toBeInTheDocument(); expect(screen.getByText('IQ-77')).toBeInTheDocument(); });
  it('supports backend pagination', async () => { let page = 1; open('/customers', 'Admin', url => { page = Number(new URL(url).searchParams.get('page')); return json({ items: [customer], totalCount: 21, page, pageSize: 10 }); }); await screen.findByText('Page 1 of 3 · 21 total'); fireEvent.click(screen.getByRole('button', { name: 'Next' })); await waitFor(() => expect(page).toBe(2)); });
  it('sends debounced search and status filters and resets page', async () => { const urls: string[] = []; open('/customers', 'Admin', url => { urls.push(url); return json({ items: [], totalCount: 0, page: 1, pageSize: 10 }); }); await screen.findByText('No customers found'); fireEvent.change(screen.getByLabelText('Search customers'), { target: { value: 'Layla' } }); fireEvent.change(screen.getByLabelText('Customer status'), { target: { value: 'Inactive' } }); await waitFor(() => expect(urls.some(url => url.includes('search=Layla') && url.includes('status=Inactive') && url.includes('page=1'))).toBe(true), { timeout: 1200 }); });
  it('renders an empty state', async () => { open('/customers', 'Admin', () => json({ items: [], totalCount: 0, page: 1, pageSize: 10 })); expect(await screen.findByText('No customers found')).toBeInTheDocument(); });
  it('renders a safe API error', async () => { open('/customers', 'Admin', () => json({ detail: 'stack' }, 500)); expect(await screen.findByRole('alert')).toHaveTextContent('Customers could not be loaded'); expect(screen.queryByText('stack')).not.toBeInTheDocument(); });
  it.each<Role>(['Admin', 'Financial Manager', 'Sales Agent'])('%s sees create and edit', async role => { open('/customers', role); expect(await screen.findByRole('link', { name: 'Create customer' })).toBeInTheDocument(); expect(await screen.findByRole('link', { name: 'Edit' })).toBeInTheDocument(); });
  it.each<Role>(['Collection Officer', 'Auditor'])('%s is read-only', async role => { open('/customers', role); await screen.findByText('Layla Hassan'); expect(screen.queryByRole('link', { name: 'Create customer' })).not.toBeInTheDocument(); expect(screen.queryByRole('link', { name: 'Edit' })).not.toBeInTheDocument(); });
  it('redirects a read-only role away from create', async () => { open('/customers/new', 'Auditor'); expect(await screen.findByRole('heading', { name: 'Access denied' })).toBeInTheDocument(); });
  it('validates required create fields', async () => { open('/customers/new'); await screen.findByRole('heading', { name: 'Create customer' }); fireEvent.click(screen.getByRole('button', { name: 'Create customer' })); expect(await screen.findByText('Full name is required.')).toBeInTheDocument(); });
  it('creates a customer and prevents duplicate submission while saving', async () => { let resolvePost!: (value: Response) => void; open('/customers/new', 'Admin', (_url, init) => init?.method === 'POST' ? new Promise(resolve => { resolvePost = resolve; }) : json(customer)); await screen.findByRole('heading', { name: 'Create customer' }); for (const [label, value] of [['Full name','New Customer'],['Identification number','NEW-1'],['Phone','0770'],['Address','Baghdad']]) fireEvent.change(screen.getByLabelText(label), { target: { value } }); fireEvent.click(screen.getByRole('button', { name: 'Create customer' })); expect(screen.getByRole('button', { name: 'Saving…' })).toBeDisabled(); resolvePost(await json(customer)); expect(await screen.findByRole('status')).toHaveTextContent('created successfully'); });
  it('shows validation and conflict responses safely', async () => { open('/customers/new', 'Admin', (_url, init) => init?.method === 'POST' ? json({ message: 'A customer with this identification number already exists.' }, 409) : json({})); await screen.findByRole('heading', { name: 'Create customer' }); for (const [label, value] of [['Full name','New Customer'],['Identification number','IQ-77'],['Phone','0770'],['Address','Baghdad']]) fireEvent.change(screen.getByLabelText(label), { target: { value } }); fireEvent.click(screen.getByRole('button', { name: 'Create customer' })); expect(await screen.findByRole('alert')).toHaveTextContent('already exists'); });
  it('loads details and handles missing customers', async () => { open('/customers/7', 'Admin', () => json(customer)); expect(await screen.findByRole('heading', { name: 'Layla Hassan' })).toBeInTheDocument(); });
  it('shows not found for a missing customer', async () => { open('/customers/999', 'Admin', () => json({}, 404)); expect(await screen.findByRole('heading', { name: 'Customer not found' })).toBeInTheDocument(); });
  it('loads edit data with immutable identity and updates', async () => { let put = false; open('/customers/7/edit', 'Admin', (_url, init) => { if (init?.method === 'PUT') { put = true; return json({ ...customer, status: 'Inactive' }); } return json(customer); }); expect(await screen.findByDisplayValue('Layla Hassan')).toHaveAttribute('readonly'); expect(screen.getByDisplayValue('IQ-77')).toHaveAttribute('readonly'); fireEvent.change(screen.getByLabelText('Status'), { target: { value: 'Inactive' } }); fireEvent.click(screen.getByRole('button', { name: 'Save changes' })); await waitFor(() => expect(put).toBe(true)); expect(await screen.findByRole('status')).toHaveTextContent('updated successfully'); });
});
