import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { App } from '../App';
import type { Role } from '../types/api';

const guarantor = { guarantorId: 9, fullName: 'Omar Ali', identificationNumber: 'G-9', phone: '+964 770-1234567', secondaryPhone: '07800000000', address: 'Baghdad', occupation: 'Engineer', workplace: 'Office', notes: 'Profile note', isActive: true, createdAt: '2026-09-01T10:00:00Z' };
const details = { guarantor, contracts: [{ contractGuarantorId: 4, contractId: 44, contractNumber: 'CNT-044', status: 'Active', guaranteeNotes: 'Historical guarantee', linkedAt: '2026-09-18T10:00:00Z' }] };
const json = (body: unknown, status = 200) => Promise.resolve(new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }));
function defaultHandler(url: string) { return url.includes('/api/guarantors/9') ? json(details) : json({ items: [guarantor], totalCount: 1, page: 1, pageSize: 10 }); }
function open(path: string, role: Role = 'Admin', handler: (url: string, init?: RequestInit) => Promise<Response> = defaultHandler) { sessionStorage.setItem('ims.auth.token', 'jwt'); vi.spyOn(globalThis, 'fetch').mockImplementation((input, init) => { const url = String(input); return url.endsWith('/api/auth/me') ? json({ id: 1, email: 'user@example.com', role }) : handler(url, init); }); history.pushState({}, '', path); render(<App />); }
function fillRequired() { fireEvent.change(screen.getByLabelText('Full name'), { target: { value: 'New Guarantor' } }); fireEvent.change(screen.getByLabelText('Identification number'), { target: { value: 'NEW-G' } }); fireEvent.change(screen.getByLabelText('Phone'), { target: { value: '+964 770-1111111' } }); fireEvent.change(screen.getByLabelText('Address'), { target: { value: 'Baghdad' } }); }

describe('Guarantors module', () => {
  it('loads guarantors and renders actual fields and Active badge', async () => { open('/guarantors'); expect(await screen.findByText('Omar Ali')).toBeInTheDocument(); expect(screen.getByText('G-9')).toBeInTheDocument(); expect(screen.getByText('+964 770-1234567')).toBeInTheDocument(); expect(screen.getByText('07800000000')).toBeInTheDocument(); expect(screen.getByText('Engineer')).toBeInTheDocument(); expect(screen.getByText('Office')).toBeInTheDocument(); expect(screen.getAllByText('Active').length).toBeGreaterThan(0); });
  it.each<Role>(['Admin', 'Financial Manager', 'Sales Agent'])('%s can create and edit', async role => { open('/guarantors', role); expect(await screen.findByRole('link', { name: 'Add guarantor' })).toBeInTheDocument(); expect(await screen.findByRole('link', { name: 'Edit' })).toBeInTheDocument(); });
  it.each<Role>(['Collection Officer', 'Auditor'])('%s is read-only', async role => { open('/guarantors', role); await screen.findByText('Omar Ali'); expect(screen.queryByRole('link', { name: 'Add guarantor' })).not.toBeInTheDocument(); expect(screen.queryByRole('link', { name: 'Edit' })).not.toBeInTheDocument(); });
  it.each<Role>(['Collection Officer', 'Auditor'])('guards create and edit routes from %s', async role => { open('/guarantors/new', role); expect(await screen.findByRole('heading', { name: 'Access denied' })).toBeInTheDocument(); });
  it('guards the edit route from a read-only role', async () => { open('/guarantors/9/edit', 'Collection Officer'); expect(await screen.findByRole('heading', { name: 'Access denied' })).toBeInTheDocument(); });
  it('uses server pagination', async () => { let page = 1; open('/guarantors', 'Admin', url => { page = Number(new URL(url).searchParams.get('page')); return json({ items: [guarantor], totalCount: 21, page, pageSize: 10 }); }); await screen.findByText(/Page 1 of 3/); fireEvent.click(screen.getByRole('button', { name: 'Next' })); await waitFor(() => expect(page).toBe(2)); });
  it('sends debounced search and active filter and resets them', async () => { const urls: string[] = []; open('/guarantors', 'Admin', url => { urls.push(url); return json({ items: [], totalCount: 0, page: 1, pageSize: 10 }); }); await screen.findByText('No guarantors found'); fireEvent.change(screen.getByLabelText('Search guarantors'), { target: { value: 'Omar' } }); fireEvent.change(screen.getByLabelText('Guarantor status'), { target: { value: 'false' } }); await waitFor(() => expect(urls.some(url => url.includes('search=Omar') && url.includes('isActive=false') && url.includes('page=1'))).toBe(true), { timeout: 1200 }); fireEvent.click(screen.getByRole('button', { name: 'Clear filters' })); await waitFor(() => expect(urls.at(-1)).not.toContain('isActive=')); });
  it('renders empty and safe list error states', async () => { open('/guarantors', 'Admin', () => json({ detail: 'SQL stack' }, 500)); expect(await screen.findByRole('alert')).toHaveTextContent('Guarantors could not be loaded'); expect(screen.queryByText('SQL stack')).not.toBeInTheDocument(); });
  it('loads details, profile fields, badge, and historical links', async () => { open('/guarantors/9'); expect(await screen.findByRole('heading', { name: 'Omar Ali' })).toBeInTheDocument(); expect(screen.getByText('Profile note')).toBeInTheDocument(); expect(screen.getByText('Historical guarantee')).toBeInTheDocument(); expect(screen.getByRole('link', { name: 'CNT-044' })).toHaveAttribute('href', '/contracts/44'); expect(screen.getAllByText('Active').length).toBeGreaterThan(0); });
  it('shows Guarantor Not Found safely', async () => { open('/guarantors/999', 'Admin', () => json({}, 404)); expect(await screen.findByRole('heading', { name: 'Guarantor Not Found' })).toBeInTheDocument(); });
  it('validates required fields and phone format', async () => { open('/guarantors/new'); await screen.findByRole('heading', { name: 'Create guarantor' }); fireEvent.change(screen.getByLabelText('Phone'), { target: { value: 'call me' } }); fireEvent.click(screen.getByRole('button', { name: 'Create guarantor' })); expect(await screen.findByText('Full name is required.')).toBeInTheDocument(); expect(screen.getByText(/optional leading/)).toBeInTheDocument(); });
  it('creates with exact DTO, optional nulls, redirects, and prevents duplicate submits', async () => { let sent: Record<string, unknown> | undefined; let resolvePost!: (response: Response) => void; open('/guarantors/new', 'Sales Agent', (url, init) => { if (init?.method === 'POST') return new Promise(resolve => { sent = JSON.parse(String(init.body)); resolvePost = resolve; }); return defaultHandler(url); }); await screen.findByRole('heading', { name: 'Create guarantor' }); fillRequired(); fireEvent.click(screen.getByRole('button', { name: 'Create guarantor' })); expect(screen.getByRole('button', { name: 'Saving…' })).toBeDisabled(); expect(sent).toEqual({ fullName: 'New Guarantor', identificationNumber: 'NEW-G', phone: '+964 770-1111111', secondaryPhone: null, address: 'Baghdad', occupation: null, workplace: null, notes: null, isActive: true }); resolvePost(await json(guarantor, 201)); expect(await screen.findByRole('status')).toHaveTextContent('created successfully'); });
  it('submits optional fields', async () => { let sent: Record<string, unknown> | undefined; open('/guarantors/new', 'Admin', (url, init) => { if (init?.method === 'POST') { sent = JSON.parse(String(init.body)); return json(guarantor, 201); } return defaultHandler(url); }); await screen.findByRole('heading', { name: 'Create guarantor' }); fillRequired(); fireEvent.change(screen.getByLabelText('Secondary phone'), { target: { value: '0780' } }); fireEvent.change(screen.getByLabelText('Occupation'), { target: { value: 'Engineer' } }); fireEvent.change(screen.getByLabelText('Workplace'), { target: { value: 'Office' } }); fireEvent.change(screen.getByLabelText(/Notes/), { target: { value: 'Note' } }); fireEvent.click(screen.getByRole('button', { name: 'Create guarantor' })); await screen.findByRole('status'); expect(sent).toMatchObject({ secondaryPhone: '0780', occupation: 'Engineer', workplace: 'Office', notes: 'Note' }); });
  it.each([[400, { errors: { Phone: ['Invalid phone.'] } }, 'correct the highlighted'], [409, { detail: 'Guarantor identification already exists.' }, 'already exists'], [500, { detail: 'SQL trace' }, 'Unable to save']] as const)('handles create error %s safely', async (status, body, message) => { open('/guarantors/new', 'Admin', (_url, init) => init?.method === 'POST' ? json(body, status) : json({})); await screen.findByRole('heading', { name: 'Create guarantor' }); fillRequired(); fireEvent.click(screen.getByRole('button', { name: 'Create guarantor' })); expect(await screen.findByRole('alert')).toHaveTextContent(message); expect(screen.queryByText('SQL trace')).not.toBeInTheDocument(); });
  it('loads edit with immutable identity and updates editable fields/status exactly', async () => { let sent: Record<string, unknown> | undefined; open('/guarantors/9/edit', 'Admin', (url, init) => { if (init?.method === 'PUT') { sent = JSON.parse(String(init.body)); return json({ ...guarantor, phone: '07700000000', isActive: false }); } return defaultHandler(url); }); expect(await screen.findByDisplayValue('Omar Ali')).toHaveAttribute('readonly'); expect(screen.getByDisplayValue('G-9')).toHaveAttribute('readonly'); fireEvent.change(screen.getByLabelText('Phone'), { target: { value: '07700000000' } }); fireEvent.change(screen.getByLabelText('Status'), { target: { value: 'false' } }); expect(screen.getByText(/Inactive guarantors cannot be selected for new contracts/)).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Save changes' })); expect(await screen.findByRole('status')).toHaveTextContent('updated successfully'); expect(sent).toMatchObject({ fullName: 'Omar Ali', identificationNumber: 'G-9', phone: '07700000000', isActive: false }); });
  it('displays Inactive badge and never exposes Delete', async () => { open('/guarantors/9', 'Admin', () => json({ ...details, guarantor: { ...guarantor, isActive: false } })); expect(await screen.findByText('Inactive')).toBeInTheDocument(); expect(screen.queryByRole('button', { name: /delete/i })).not.toBeInTheDocument(); expect(screen.queryByRole('link', { name: /delete/i })).not.toBeInTheDocument(); });
  it('handles edit conflict safely', async () => { open('/guarantors/9/edit', 'Admin', (url, init) => init?.method === 'PUT' ? json({ detail: 'Guarantor name and identification number cannot be changed.' }, 409) : defaultHandler(url)); await screen.findByDisplayValue('Omar Ali'); fireEvent.click(screen.getByRole('button', { name: 'Save changes' })); expect(await screen.findByRole('alert')).toHaveTextContent('cannot be changed'); });
});
