import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { App } from '../App';
import type { Role } from '../types/api';

const installment = { installmentId: 31, installmentNumber: 2, dueDate: '2026-09-10', amount: 100, paidAmount: 40, remainingAmount: 60, status: 'Partially Paid', isPastDue: true, isOpen: true, contract: { contractId: 44, contractNumber: 'CNT-044', status: 'Active' }, customer: { customerId: 7, fullName: 'Layla Hassan', phone: '07701234567', secondaryPhone: null } };
const page = { items: [installment], totalCount: 1, page: 1, pageSize: 10, asOfUtcDate: '2026-09-19' };
const details = { installment, asOfUtcDate: '2026-09-19' };
const json = (body: unknown, status = 200) => Promise.resolve(new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }));
function handler(url: string) { return url.includes('/api/installments/31') ? json(details) : json(page); }
function open(path: string, role: Role = 'Admin', request: (url: string, init?: RequestInit) => Promise<Response> = handler) { sessionStorage.setItem('ims.auth.token', 'jwt'); vi.spyOn(globalThis, 'fetch').mockImplementation((input, init) => { const url = String(input); return url.endsWith('/api/auth/me') ? json({ id: 1, email: 'user@example.com', role }) : request(url, init); }); history.pushState({}, '', path); render(<App />); }

describe('Installments module', () => {
  it.each<Role>(['Admin', 'Financial Manager', 'Sales Agent', 'Collection Officer', 'Auditor'])('%s can read installments', async role => { open('/installments', role); expect(await screen.findByText('Layla Hassan')).toBeInTheDocument(); expect(screen.getByRole('link', { name: 'Installments' })).toBeInTheDocument(); });
  it('renders actual list fields, amounts, due date, and status', async () => { open('/installments'); await screen.findByText('Layla Hassan'); expect(screen.getByText('CNT-044')).toBeInTheDocument(); expect(screen.getByText('2026-09-10')).toBeInTheDocument(); expect(screen.getByText('100.00')).toBeInTheDocument(); expect(screen.getByText('40.00')).toBeInTheDocument(); expect(screen.getByText('60.00')).toBeInTheDocument(); expect(screen.getAllByText('Partially Paid').length).toBeGreaterThan(1); expect(screen.getByText('Past due')).toBeInTheDocument(); });
  it('uses server pagination', async () => { let requestedPage = 1; open('/installments', 'Admin', url => { requestedPage = Number(new URL(url).searchParams.get('page')); return json({ ...page, totalCount: 21, page: requestedPage }); }); await screen.findByText(/Page 1 of 3/); fireEvent.click(screen.getByRole('button', { name: 'Next' })); await waitFor(() => expect(requestedPage).toBe(2)); });
  it('sends every supported filter to the server', async () => { const urls: string[] = []; open('/installments?contractId=44', 'Admin', url => { urls.push(url); return json({ ...page, items: [] }); }); await screen.findByText('No installments found'); fireEvent.change(screen.getByLabelText('Search installments'), { target: { value: 'Layla' } }); fireEvent.change(screen.getByLabelText('Installment customer ID'), { target: { value: '7' } }); fireEvent.change(screen.getByLabelText('Installment status'), { target: { value: 'Pending' } }); fireEvent.change(screen.getByLabelText('Installment number'), { target: { value: '2' } }); fireEvent.change(screen.getByLabelText('Due from'), { target: { value: '2026-09-01' } }); fireEvent.change(screen.getByLabelText('Due to'), { target: { value: '2026-09-30' } }); fireEvent.click(screen.getByLabelText('Past due only')); fireEvent.click(screen.getByLabelText('Open only')); await waitFor(() => expect(urls.some(url => url.includes('search=Layla') && url.includes('contractId=44') && url.includes('customerId=7') && url.includes('status=Pending') && url.includes('installmentNumber=2') && url.includes('dueFrom=2026-09-01') && url.includes('dueTo=2026-09-30') && url.includes('pastDueOnly=true') && url.includes('openOnly=true'))).toBe(true), { timeout: 1500 }); });
  it('clears filters', async () => { const urls: string[] = []; open('/installments?contractId=44', 'Admin', url => { urls.push(url); return json({ ...page, items: [] }); }); await screen.findByText('No installments found'); fireEvent.click(screen.getByRole('button', { name: 'Clear filters' })); await waitFor(() => expect(urls.at(-1)).not.toContain('contractId=')); });
  it('shows an empty state and a safe retryable error', async () => { open('/installments', 'Admin', () => json({ detail: 'SQL stack trace' }, 500)); expect(await screen.findByRole('alert')).toHaveTextContent('Installments could not be loaded'); expect(screen.queryByText(/SQL stack/)).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Try again' })).toBeInTheDocument(); });
  it('loads detail with amounts, contract link, and server metadata', async () => { open('/installments/31'); expect(await screen.findByRole('heading', { name: 'Installment 2' })).toBeInTheDocument(); expect(screen.getByRole('link', { name: 'CNT-044' })).toHaveAttribute('href', '/contracts/44'); expect(screen.getByText('Yes (reported by server)')).toBeInTheDocument(); expect(screen.getByText('Partially Paid')).toBeInTheDocument(); expect(screen.getByText('07701234567')).toBeInTheDocument(); });
  it('shows Installment Not Found safely', async () => { open('/installments/999', 'Admin', () => json({}, 404)); expect(await screen.findByRole('heading', { name: 'Installment Not Found' })).toBeInTheDocument(); });
  it('never exposes installment mutation controls', async () => { open('/installments/31'); await screen.findByRole('heading', { name: 'Installment 2' }); for (const name of [/edit/i, /delete/i, /mark paid/i, /change status/i, /change due date/i, /manual allocation/i]) { expect(screen.queryByRole('button', { name })).not.toBeInTheDocument(); expect(screen.queryByRole('link', { name })).not.toBeInTheDocument(); } });
  it('does not convert a Pending status when the server reports past due', async () => { open('/installments', 'Admin', () => json({ ...page, items: [{ ...installment, status: 'Pending', isPastDue: true }] })); await screen.findByText('Layla Hassan'); expect(screen.getAllByText('Pending').length).toBeGreaterThan(1); expect(screen.getByText('Past due')).toBeInTheDocument(); expect(screen.getAllByText('Overdue')).toHaveLength(1); });
  it.each<Role>(['Admin', 'Financial Manager', 'Collection Officer'])('%s can navigate to a contract payment without installment ID', async role => { open('/installments/31', role); const link = await screen.findByRole('link', { name: 'Record payment' }); expect(link).toHaveAttribute('href', '/payments/new?contractId=44'); expect(link.getAttribute('href')).not.toContain('installmentId'); });
  it.each<Role>(['Sales Agent', 'Auditor'])('hides payment action from %s', async role => { open('/installments/31', role); await screen.findByRole('heading', { name: 'Installment 2' }); expect(screen.queryByRole('link', { name: 'Record payment' })).not.toBeInTheDocument(); });
  it('hides payment action when the contract is not Active', async () => { open('/installments/31', 'Admin', () => json({ ...details, installment: { ...installment, contract: { ...installment.contract, status: 'Completed' } } })); await screen.findByRole('heading', { name: 'Installment 2' }); expect(screen.queryByRole('link', { name: 'Record payment' })).not.toBeInTheDocument(); });
});
