import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { App } from '../App';
import type { Role } from '../types/api';

const payment = { paymentId: 81, paymentReference: 'PAY-081', contractId: 44, receivedByUserId: 3, paymentDate: '2026-09-19T09:30:00Z', amount: 25.5, paymentMethod: 'Cash', notes: 'Branch receipt' };
const contract = { contractId: 44, contractNumber: 'CNT-044', customerId: 7, customerName: 'Layla Hassan', createdByUserId: 1, contractDate: '2026-09-18T00:00:00Z', totalAmount: 240, downPayment: 24, remainingAmount: 216, numberOfInstallments: 12, status: 'Active', createdAt: '2026-09-18T10:00:00Z' } as const;
const contractDetails = { contract, items: [], guarantors: [], installments: [{ installmentId: 1, installmentNumber: 1, dueDate: '2026-10-18', amount: 18, paidAmount: 0, remainingAmount: 18, status: 'Pending' }] };
const details = { payment, contract: { contractId: 44, contractNumber: 'CNT-044', customerId: 7, customerName: 'Layla Hassan', remainingAmount: 190.5, status: 'Active' }, allocations: [{ paymentAllocationId: 91, allocatedAmount: 18, createdAt: '2026-09-19T09:30:00Z', installment: { installmentId: 1, installmentNumber: 1, dueDate: '2026-10-18', amount: 18, paidAmount: 18, remainingAmount: 0, status: 'Paid' } }, { paymentAllocationId: 92, allocatedAmount: 7.5, createdAt: '2026-09-19T09:30:00Z', installment: { installmentId: 2, installmentNumber: 2, dueDate: '2026-11-18', amount: 18, paidAmount: 7.5, remainingAmount: 10.5, status: 'Partially Paid' } }] };
const json = (body: unknown, status = 200) => Promise.resolve(new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }));
function handler(url: string, init?: RequestInit) { if (url.includes('/api/contracts/44')) return json(contractDetails); if (url.includes('/api/contracts?')) return json({ items: [contract], totalCount: 1, page: 1, pageSize: 10 }); if (url.includes('/api/payments/81')) return json(details); if (init?.method === 'POST') return json(details, 201); return json({ items: [payment], totalCount: 1, page: 1, pageSize: 10 }); }
function open(path: string, role: Role = 'Admin', request: (url: string, init?: RequestInit) => Promise<Response> = handler) { sessionStorage.setItem('ims.auth.token', 'jwt'); vi.spyOn(globalThis, 'fetch').mockImplementation((input, init) => { const url = String(input); return url.endsWith('/api/auth/me') ? json({ id: 1, email: 'user@example.com', role }) : request(url, init); }); history.pushState({}, '', path); render(<App />); }
async function selectContract() { await screen.findByRole('option', { name: /CNT-044/ }); fireEvent.change(screen.getByLabelText('Contract results'), { target: { value: '44' } }); await screen.findByText('Current installment schedule'); }
async function validForm() { await selectContract(); fireEvent.change(screen.getByLabelText('Payment reference'), { target: { value: 'PAY-NEW' } }); fireEvent.change(screen.getByLabelText('Payment method'), { target: { value: 'Cash' } }); fireEvent.change(screen.getByLabelText('Amount'), { target: { value: '25.50' } }); }

describe('Payments module', () => {
  it.each<Role>(['Admin', 'Financial Manager', 'Collection Officer'])('%s can read and create payments', async role => { open('/payments', role); expect(await screen.findByText('PAY-081')).toBeInTheDocument(); expect(screen.getByRole('link', { name: 'Record payment' })).toBeInTheDocument(); });
  it('allows Auditor read-only payment access', async () => { open('/payments', 'Auditor'); expect(await screen.findByText('PAY-081')).toBeInTheDocument(); expect(screen.queryByRole('link', { name: 'Record payment' })).not.toBeInTheDocument(); });
  it('denies Sales Agent payment access', async () => { open('/payments', 'Sales Agent'); expect(await screen.findByRole('heading', { name: 'Access denied' })).toBeInTheDocument(); expect(screen.queryByRole('link', { name: 'Payments' })).not.toBeInTheDocument(); });
  it.each<Role>(['Auditor', 'Sales Agent'])('guards create route from %s', async role => { open('/payments/new', role); expect(await screen.findByRole('heading', { name: 'Access denied' })).toBeInTheDocument(); });
  it('renders actual list fields', async () => { open('/payments'); await screen.findByText('PAY-081'); expect(screen.getByText('25.50')).toBeInTheDocument(); expect(screen.getByText('Cash')).toBeInTheDocument(); expect(screen.getByText('User #3')).toBeInTheDocument(); expect(screen.getByText('44')).toBeInTheDocument(); });
  it('uses server pagination', async () => { let page = 1; open('/payments', 'Admin', url => { page = Number(new URL(url).searchParams.get('page')); return json({ items: [payment], totalCount: 21, page, pageSize: 10 }); }); await screen.findByText(/Page 1 of 3/); fireEvent.click(screen.getByRole('button', { name: 'Next' })); await waitFor(() => expect(page).toBe(2)); });
  it('sends supported search and ID filters', async () => { const urls: string[] = []; open('/payments', 'Admin', url => { urls.push(url); return json({ items: [], totalCount: 0, page: 1, pageSize: 10 }); }); await screen.findByText('No payments found'); fireEvent.change(screen.getByLabelText('Search payments'), { target: { value: 'Cash' } }); fireEvent.change(screen.getByLabelText('Payment contract ID'), { target: { value: '44' } }); fireEvent.change(screen.getByLabelText('Payment customer ID'), { target: { value: '7' } }); await waitFor(() => expect(urls.some(url => url.includes('search=Cash') && url.includes('contractId=44') && url.includes('customerId=7'))).toBe(true), { timeout: 1200 }); });
  it('renders list empty and safe error states', async () => { open('/payments', 'Admin', () => json({ detail: 'database trace' }, 500)); expect(await screen.findByRole('alert')).toHaveTextContent('Payments could not be loaded'); expect(screen.queryByText('database trace')).not.toBeInTheDocument(); });
  it('renders payment detail and backend allocations', async () => { open('/payments/81'); expect(await screen.findByRole('heading', { name: 'PAY-081' })).toBeInTheDocument(); expect(screen.getByText('Branch receipt')).toBeInTheDocument(); expect(screen.getAllByText('18.00').length).toBeGreaterThan(0); expect(screen.getAllByText('7.50').length).toBeGreaterThan(0); expect(screen.getByText('Partially Paid')).toBeInTheDocument(); expect(screen.getByText('These are the allocations returned by the server for this receipt.')).toBeInTheDocument(); });
  it('shows Payment Not Found safely', async () => { open('/payments/999', 'Admin', () => json({}, 404)); expect(await screen.findByRole('heading', { name: 'Payment Not Found' })).toBeInTheDocument(); });
  it('queries only Active contracts with bounded pagination', async () => { const urls: string[] = []; open('/payments/new', 'Admin', (url, init) => { urls.push(url); return handler(url, init); }); await screen.findByRole('option', { name: /CNT-044/ }); expect(urls.some(url => url.includes('/api/contracts?') && url.includes('status=Active') && url.includes('pageSize=10'))).toBe(true); });
  it('shows selected contract summary and read-only schedule', async () => { open('/payments/new'); await selectContract(); expect(screen.getAllByText('Layla Hassan').length).toBeGreaterThan(0); expect(screen.getAllByText('216.00').length).toBeGreaterThan(0); expect(screen.getByText('Current installment schedule')).toBeInTheDocument(); expect(screen.getByText('Allocation will be determined by the server. No installment allocation is calculated in this form.')).toBeInTheDocument(); });
  it('preselects a valid Active contract from query', async () => { open('/payments/new?contractId=44'); expect(await screen.findByText('Current installment schedule')).toBeInTheDocument(); expect(screen.getAllByText('CNT-044').length).toBeGreaterThan(0); });
  it('rejects a non-Active preselected contract in the UI', async () => { open('/payments/new?contractId=44', 'Admin', url => url.includes('/api/contracts/44') ? json({ ...contractDetails, contract: { ...contract, status: 'Completed' } }) : handler(url)); expect(await screen.findByText('The selected contract is not Active and cannot receive payments.')).toBeInTheDocument(); });
  it('validates required and decimal fields without calculating allocations', async () => { open('/payments/new'); await screen.findByRole('heading', { name: 'Record payment' }); fireEvent.change(screen.getByLabelText('Amount'), { target: { value: '1.234' } }); fireEvent.click(screen.getByRole('button', { name: 'Record payment' })); expect(await screen.findByRole('alert')).toHaveTextContent('correct the highlighted'); expect(screen.getByText('Use a positive amount with at most two decimal places.')).toBeInTheDocument(); expect(screen.queryByText(/allocated to installment/i)).not.toBeInTheDocument(); });
  it('warns without silently changing an overpayment', async () => { open('/payments/new'); await selectContract(); const amount = screen.getByLabelText('Amount'); fireEvent.change(amount, { target: { value: '217' } }); expect(screen.getByText(/exceeds the displayed remaining balance/)).toBeInTheDocument(); expect(amount).toHaveValue('217'); });
  it('sends exact create DTO and prevents duplicate submission', async () => { let sent: Record<string, unknown> | undefined; let resolvePost!: (response: Response) => void; open('/payments/new', 'Collection Officer', (url, init) => { if (init?.method === 'POST') return new Promise(resolve => { sent = JSON.parse(String(init.body)); resolvePost = resolve; }); return handler(url, init); }); await validForm(); fireEvent.change(screen.getByLabelText(/Payment date/), { target: { value: '2026-09-19T12:30' } }); fireEvent.change(screen.getByLabelText(/Notes/), { target: { value: 'Receipt note' } }); fireEvent.click(screen.getByRole('button', { name: 'Record payment' })); expect(screen.getByRole('button', { name: 'Recording…' })).toBeDisabled(); expect(sent).toEqual({ contractId: 44, paymentReference: 'PAY-NEW', paymentDate: '2026-09-19T12:30:00.000Z', amount: 25.5, paymentMethod: 'Cash', notes: 'Receipt note' }); resolvePost(await json(details, 201)); expect(await screen.findByRole('status')).toHaveTextContent('Payment recorded successfully'); });
  it('uses null optional fields and displays authoritative allocation after success', async () => { let sent: Record<string, unknown> | undefined; open('/payments/new', 'Admin', (url, init) => { if (init?.method === 'POST') { sent = JSON.parse(String(init.body)); return json(details, 201); } return handler(url, init); }); await validForm(); fireEvent.click(screen.getByRole('button', { name: 'Record payment' })); expect(await screen.findByRole('heading', { name: 'PAY-081' })).toBeInTheDocument(); expect(sent).toMatchObject({ paymentDate: null, notes: null }); expect(screen.getAllByText('7.50').length).toBeGreaterThan(0); });
  it('shows Completed only from backend detail response', async () => { const completed = { ...details, contract: { ...details.contract, remainingAmount: 0, status: 'Completed' } }; open('/payments/new', 'Admin', (url, init) => init?.method === 'POST' || url.includes('/api/payments/81') ? json(completed, init?.method === 'POST' ? 201 : 200) : handler(url, init)); await validForm(); fireEvent.click(screen.getByRole('button', { name: 'Record payment' })); expect(await screen.findByText('Completed')).toBeInTheDocument(); expect(screen.getAllByText('0.00').length).toBeGreaterThan(0); });
  it.each([[400, { errors: { Amount: ['Use a positive amount.'] } }, 'Use a positive amount.'], [403, {}, 'Access Denied'], [404, {}, 'Contract Not Found'], [500, { detail: 'SQL trace' }, 'Unable to record the payment']] as const)('handles create error %s safely', async (status, body, message) => { open('/payments/new', 'Admin', (url, init) => init?.method === 'POST' ? json(body, status) : handler(url, init)); await validForm(); fireEvent.click(screen.getByRole('button', { name: 'Record payment' })); expect(await screen.findByRole('alert')).toHaveTextContent(message); expect(screen.queryByText('SQL trace')).not.toBeInTheDocument(); });
  it.each(['Payment amount exceeds the payable outstanding balance.', 'Payments require an Active contract.'])('shows safe 409 conflict: %s', async message => { open('/payments/new', 'Admin', (url, init) => init?.method === 'POST' ? json({ detail: message }, 409) : handler(url, init)); await validForm(); fireEvent.click(screen.getByRole('button', { name: 'Record payment' })); expect(await screen.findByRole('alert')).toHaveTextContent(message); });
});
