import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { App } from '../App';
import type { Role } from '../types/api';

const product = { productId: 12, productCode: 'REF-001', name: 'Refrigerator', description: 'Large appliance', cashPrice: 1250.5, installmentPrice: 1400, isActive: true, createdAt: '2026-09-18T10:00:00Z' };
const json = (body: unknown, status = 200) => Promise.resolve(new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }));
function open(path: string, role: Role = 'Admin', handler?: (url: string, init?: RequestInit) => Promise<Response>) {
  sessionStorage.setItem('ims.auth.token', 'jwt');
  vi.spyOn(globalThis, 'fetch').mockImplementation((input, init) => { const url = String(input); if (url.endsWith('/api/auth/me')) return json({ id: 1, email: 'user@example.com', role }); return handler ? handler(url, init) : json({ items: [product], totalCount: 1, page: 1, pageSize: 10 }); });
  history.pushState({}, '', path); render(<App />);
}
function completeRequiredFields() {
  fireEvent.change(screen.getByLabelText('Product code'), { target: { value: 'NEW-1' } });
  fireEvent.change(screen.getByLabelText('Name'), { target: { value: 'New product' } });
  fireEvent.change(screen.getByLabelText('Cash price'), { target: { value: '120.50' } });
}

describe('Products module', () => {
  it('loads and renders product rows with formatted prices', async () => { open('/products'); expect(await screen.findByText('Refrigerator')).toBeInTheDocument(); expect(screen.getByText('REF-001')).toBeInTheDocument(); expect(screen.getByText('1,250.50')).toBeInTheDocument(); });
  it('supports backend pagination', async () => { let page = 1; open('/products', 'Admin', url => { page = Number(new URL(url).searchParams.get('page')); return json({ items: [product], totalCount: 21, page, pageSize: 10 }); }); await screen.findByText(/Page 1 of 3/); fireEvent.click(screen.getByRole('button', { name: 'Next' })); await waitFor(() => expect(page).toBe(2)); });
  it('sends debounced search and availability filters and resets page', async () => { const urls: string[] = []; open('/products', 'Admin', url => { urls.push(url); return json({ items: [], totalCount: 0, page: 1, pageSize: 10 }); }); await screen.findByText('No products found'); fireEvent.change(screen.getByLabelText('Search products'), { target: { value: 'REF' } }); fireEvent.change(screen.getByLabelText('Product availability'), { target: { value: 'false' } }); await waitFor(() => expect(urls.some(url => url.includes('search=REF') && url.includes('isActive=false') && url.includes('page=1'))).toBe(true), { timeout: 1200 }); });
  it('clears filters', async () => { const urls: string[] = []; open('/products', 'Admin', url => { urls.push(url); return json({ items: [], totalCount: 0, page: 1, pageSize: 10 }); }); await screen.findByText('No products found'); fireEvent.change(screen.getByLabelText('Product availability'), { target: { value: 'true' } }); fireEvent.click(screen.getByRole('button', { name: 'Clear filters' })); await waitFor(() => expect(urls.at(-1)).not.toContain('isActive=')); });
  it('renders an empty state', async () => { open('/products', 'Admin', () => json({ items: [], totalCount: 0, page: 1, pageSize: 10 })); expect(await screen.findByText('No products found')).toBeInTheDocument(); });
  it('renders a safe API error', async () => { open('/products', 'Admin', () => json({ detail: 'database stack' }, 500)); expect(await screen.findByRole('alert')).toHaveTextContent('Products could not be loaded'); expect(screen.queryByText('database stack')).not.toBeInTheDocument(); });
  it.each<Role>(['Admin', 'Financial Manager'])('%s sees create and edit', async role => { open('/products', role); expect(await screen.findByRole('link', { name: 'Create product' })).toBeInTheDocument(); await screen.findByText('Refrigerator'); expect(screen.getByRole('link', { name: 'Edit' })).toBeInTheDocument(); });
  it.each<Role>(['Sales Agent', 'Collection Officer', 'Auditor'])('%s is read-only', async role => { open('/products', role); await screen.findByText('Refrigerator'); expect(screen.queryByRole('link', { name: 'Create product' })).not.toBeInTheDocument(); expect(screen.queryByRole('link', { name: 'Edit' })).not.toBeInTheDocument(); });
  it.each<Role>(['Sales Agent', 'Collection Officer', 'Auditor'])('guards write routes from %s', async role => { open('/products/new', role); expect(await screen.findByRole('heading', { name: 'Access denied' })).toBeInTheDocument(); });
  it('keeps products protected by authentication', async () => { history.pushState({}, '', '/products'); render(<App />); expect(await screen.findByRole('heading', { name: 'Welcome back' })).toBeInTheDocument(); });
  it('validates required fields and exact decimal rules', async () => { open('/products/new'); await screen.findByRole('heading', { name: 'Create product' }); fireEvent.click(screen.getByRole('button', { name: 'Create product' })); expect(await screen.findByText('Product code is required.')).toBeInTheDocument(); fireEvent.change(screen.getByLabelText(/^Cash price/), { target: { value: '1.234' } }); fireEvent.click(screen.getByRole('button', { name: 'Create product' })); expect(await screen.findByText(/at most two decimal places/)).toBeInTheDocument(); });
  it('creates with nullable installment price and disables repeat submission', async () => { let sent: Record<string, unknown> | undefined; let resolvePost!: (value: Response) => void; open('/products/new', 'Admin', (_url, init) => init?.method === 'POST' ? new Promise(resolve => { sent = JSON.parse(String(init.body)); resolvePost = resolve; }) : json(product)); await screen.findByRole('heading', { name: 'Create product' }); completeRequiredFields(); fireEvent.click(screen.getByRole('button', { name: 'Create product' })); expect(screen.getByRole('button', { name: 'Saving…' })).toBeDisabled(); expect(sent?.installmentPrice).toBeNull(); resolvePost(await json(product, 201)); expect(await screen.findByRole('status')).toHaveTextContent('created successfully'); });
  it('shows duplicate product code safely', async () => { open('/products/new', 'Admin', (_url, init) => init?.method === 'POST' ? json({ message: 'internal conflict detail' }, 409) : json(product)); await screen.findByRole('heading', { name: 'Create product' }); completeRequiredFields(); fireEvent.click(screen.getByRole('button', { name: 'Create product' })); expect(await screen.findByRole('alert')).toHaveTextContent('product code already exists'); expect(screen.queryByText('internal conflict detail')).not.toBeInTheDocument(); });
  it('loads all product details', async () => { open('/products/12', 'Admin', () => json(product)); expect(await screen.findByRole('heading', { name: 'Refrigerator' })).toBeInTheDocument(); expect(screen.getByText('Large appliance')).toBeInTheDocument(); expect(screen.getByText('1,250.50')).toBeInTheDocument(); });
  it('shows Product Not Found for a missing product', async () => { open('/products/999', 'Admin', () => json({}, 404)); expect(await screen.findByRole('heading', { name: 'Product Not Found' })).toBeInTheDocument(); });
  it('shows Access Denied for a backend detail 403', async () => { open('/products/12', 'Admin', () => json({}, 403)); expect(await screen.findByRole('heading', { name: 'Access Denied' })).toBeInTheDocument(); });
  it('loads editable values and updates fields and status', async () => { let body: Record<string, unknown> | undefined; open('/products/12/edit', 'Financial Manager', (_url, init) => { if (init?.method === 'PUT') { body = JSON.parse(String(init.body)); return json({ ...product, ...body }); } return json(product); }); expect(await screen.findByDisplayValue('REF-001')).not.toHaveAttribute('readonly'); fireEvent.change(screen.getByLabelText('Product code'), { target: { value: 'REF-EDIT' } }); fireEvent.click(screen.getByLabelText('Active')); fireEvent.click(screen.getByRole('button', { name: 'Save changes' })); await waitFor(() => expect(body).toMatchObject({ productCode: 'REF-EDIT', isActive: false })); expect(await screen.findByRole('status')).toHaveTextContent('updated successfully'); });
  it('maps backend validation to the edit field safely', async () => { open('/products/12/edit', 'Admin', (_url, init) => init?.method === 'PUT' ? json({ errors: { CashPrice: ['Backend price validation.'] } }, 400) : json(product)); await screen.findByDisplayValue('REF-001'); fireEvent.click(screen.getByRole('button', { name: 'Save changes' })); expect(await screen.findByRole('alert')).toHaveTextContent('correct the highlighted fields'); expect(screen.getByText('Backend price validation.')).toBeInTheDocument(); });
});
