import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { App } from '../App';
import type { Role } from '../types/api';

const user = (role: Role) => ({ id: 1, email: 'user@example.com', role });
const response = (body: unknown, status = 200) => Promise.resolve(new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }));
const customer = { customerId: 7, fullName: 'Ada Customer', phone: '0770', status: 'Active' };
const contract = { contractId: 9, contractNumber: 'CNT-9', customer, contractDate: '2026-09-01T00:00:00Z', totalAmount: 120, downPayment: 20, remainingAmount: 73, status: 'Active', numberOfInstallments: 12, paidInstallmentCount: 3, openInstallmentCount: 9 };
const payment = { paymentId: 4, paymentReference: 'PAY-4', paymentDate: '2026-09-10T12:00:00Z', amount: 27, paymentMethod: 'Cash', contractId: 9, contractNumber: 'CNT-9', customer, receivedByUserId: 1, receivedByName: 'Admin', allocatedTotal: 27 };
const installment = { installmentId: 5, installmentNumber: 2, dueDate: '2026-09-01', amount: 10, paidAmount: 3, remainingAmount: 7, status: 'Partially Paid', isPastDue: true, isOpen: true, contract: { contractId: 9, contractNumber: 'CNT-9', status: 'Active' }, customer: { customerId: 7, fullName: 'Ada Customer', phone: '0770', secondaryPhone: null } };
const page = <T,>(items: T[]) => ({ items, totalCount: items.length, page: 1, pageSize: 10, asOfUtcDate: '2026-09-20' });
function go(path: string, role: Role, report: (url: string) => Promise<Response>) { sessionStorage.setItem('ims.auth.token', 'jwt'); vi.spyOn(globalThis, 'fetch').mockImplementation(input => { const url=String(input); return url.endsWith('/api/auth/me') ? response(user(role)) : report(url); }); history.pushState({},'',path); render(<App/>); }

describe('Reports module', () => {
  it.each([
    ['Admin', true], ['Financial Manager', true], ['Auditor', true], ['Collection Officer', false],
  ] as [Role,boolean][])('shows exact landing access for %s', async (role, core) => { go('/reports',role,()=>response({})); expect(await screen.findByRole('heading',{name:'Reports'})).toBeInTheDocument(); const summary=screen.queryByRole('link',{name:/Summary/}); if(core) expect(summary).toBeInTheDocument(); else expect(summary).not.toBeInTheDocument(); expect(screen.getByRole('link',{name:/Outstanding balances/})).toBeInTheDocument(); });
  it('denies Sales Agent and hides Reports navigation', async () => { go('/reports','Sales Agent',()=>response({})); expect(await screen.findByRole('heading',{name:'Access denied'})).toBeInTheDocument(); expect(screen.queryByRole('link',{name:'Reports'})).not.toBeInTheDocument(); });
  it('renders every summary value supplied by the backend', async () => { const summary={totalCustomers:11,activeCustomers:10,totalProducts:8,activeProducts:7,totalContracts:6,contractsByStatus:{Active:4,Draft:2},completedContracts:1,totalContractValue:901,totalFinancedPrincipal:801,totalContractRemaining:701,activeContractRemaining:601,totalPaymentsReceived:501,openInstallmentCount:9,openInstallmentBalance:401,pastDueInstallmentCount:3,pastDueInstallmentBalance:301,asOfUtcDate:'2026-09-20'}; go('/reports/summary','Admin',()=>response(summary)); expect(await screen.findByText('901.00')).toBeInTheDocument(); expect(screen.getByText('301.00')).toBeInTheDocument(); expect(screen.getByText(/2026-09-20/)).toBeInTheDocument(); });
  it('sends supported contract filters and renders authoritative remaining value', async () => { let requested=''; go('/reports/contracts','Admin',url=>{requested=url;return response(page([contract]))}); expect(await screen.findByText('73.00')).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Report contract status'),{target:{value:'Active'}}); fireEvent.change(screen.getByLabelText('Report date from'),{target:{value:'2026-09-01'}}); await waitFor(()=>expect(requested).toContain('status=Active')); expect(requested).toContain('dateFrom=2026-09-01'); expect(screen.getByRole('link',{name:'CNT-9'})).toHaveAttribute('href','/contracts/9'); });
  it('renders payment context, links, and backend allocation total', async () => { go('/reports/payments','Auditor',()=>response(page([payment]))); expect(await screen.findByText('PAY-4')).toHaveAttribute('href','/payments/4'); expect(screen.getAllByText('27.00')).toHaveLength(2); expect(screen.getByRole('link',{name:'Ada Customer'})).toHaveAttribute('href','/customers/7'); expect(screen.queryByRole('button',{name:/delete|edit|record/i})).not.toBeInTheDocument(); });
  it('allows Collection Officer outstanding data and displays the backend as-of date', async () => { go('/reports/outstanding','Collection Officer',()=>response(page([installment]))); expect(await screen.findByText('7.00')).toBeInTheDocument(); expect(screen.getByText('Past due')).toBeInTheDocument(); expect(screen.getByText(/2026-09-20/)).toBeInTheDocument(); });
  it('renders dedicated customer and contract statements', async () => { const totals={contractRemaining:73,installmentRemaining:7,installmentPaid:3,paymentsReceived:27,allocationsTotal:27}; go('/reports/customers/7/statement','Collection Officer',()=>response({customer,contracts:page([contract]),installments:page([installment]),payments:page([payment]),totals,asOfUtcDate:'2026-09-20'})); expect(await screen.findByRole('heading',{name:'Customer statement'})).toBeInTheDocument(); expect((await screen.findAllByText('73.00')).length).toBeGreaterThan(0); });
  it('shows safe statement 404 and never renders server internals', async () => { go('/reports/contracts/999/statement','Admin',()=>response({detail:'SQL connection string secret'},404)); expect(await screen.findByRole('heading',{name:'Statement not found'})).toBeInTheDocument(); expect(screen.queryByText(/SQL|connection string|secret/i)).not.toBeInTheDocument(); });
});
