import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { App } from '../App';
import type { Role } from '../types/api';

const admin={id:1,email:'admin@example.com',role:'Admin' as Role};
const account={userId:2,username:'ada',email:'ada@example.com',fullName:'Ada User',role:'Sales Agent' as Role,isActive:true,createdAt:'2026-09-20T10:00:00Z'};
const roles=[{roleId:1,roleName:'Admin',description:'Administrators'},{roleId:2,roleName:'Financial Manager',description:null},{roleId:3,roleName:'Sales Agent',description:null},{roleId:4,roleName:'Collection Officer',description:null},{roleId:5,roleName:'Auditor',description:null}];
const json=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}}));
function go(path:string,role:Role,handler:(url:string,init?:RequestInit)=>Promise<Response>){sessionStorage.setItem('ims.auth.token','jwt');vi.spyOn(globalThis,'fetch').mockImplementation((input,init)=>String(input).endsWith('/api/auth/me')?json({...admin,role}):handler(String(input),init));history.pushState({},'',path);render(<App/>)}
function normal(url:string){if(url.endsWith('/api/roles'))return json(roles);if(url.includes('/api/users?'))return json({items:[account],totalCount:11,page:1,pageSize:10});return json(account)}

describe('Users management',()=>{
  it('shows Users navigation and the list to Admin',async()=>{go('/users','Admin',url=>normal(url));expect(await screen.findByRole('heading',{name:'Users'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'Users'})).toBeInTheDocument();expect(await screen.findByText('Ada User')).toBeInTheDocument();expect(screen.getByText('ada@example.com')).toBeInTheDocument();expect(screen.getAllByText('Sales Agent').length).toBeGreaterThan(0);expect(screen.getAllByText('Active').length).toBeGreaterThan(0);expect(screen.queryByRole('button',{name:/delete/i})).not.toBeInTheDocument()});
  it.each(['Financial Manager','Sales Agent','Collection Officer','Auditor'] as Role[])('hides navigation and denies %s',async role=>{go('/users',role,url=>normal(url));expect(await screen.findByRole('heading',{name:'Access denied'})).toBeInTheDocument();expect(screen.queryByRole('link',{name:'Users'})).not.toBeInTheDocument()});
  it.each(['/users/new','/users/2','/users/2/edit'])('denies non-Admin route %s',async path=>{go(path,'Auditor',url=>normal(url));expect(await screen.findByRole('heading',{name:'Access denied'})).toBeInTheDocument()});
  it('sends supported filters and server pagination',async()=>{let requested='';go('/users','Admin',url=>{requested=url;return normal(url)});await screen.findByText('Ada User');fireEvent.change(screen.getByLabelText('Search users'),{target:{value:'Ada'}});fireEvent.change(screen.getByLabelText('User role filter'),{target:{value:'Sales Agent'}});fireEvent.change(screen.getByLabelText('User status filter'),{target:{value:'false'}});await waitFor(()=>expect(requested).toContain('search=Ada'));expect(requested).toContain('role=Sales+Agent');expect(requested).toContain('isActive=false');fireEvent.click(screen.getByRole('button',{name:'Next'}));await waitFor(()=>expect(requested).toContain('page=2'))});
  it('renders an empty list and a safe server error',async()=>{go('/users','Admin',url=>url.endsWith('/api/roles')?json(roles):json({items:[],totalCount:0,page:1,pageSize:10}));expect(await screen.findByRole('heading',{name:'No users found'})).toBeInTheDocument()});
  it('renders details and safe 404 without passwords',async()=>{go('/users/2','Admin',url=>normal(url));expect(await screen.findByText('Ada User')).toBeInTheDocument();expect(screen.getByText('ada@example.com')).toBeInTheDocument();expect(screen.queryByText(/password/i)).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:/delete/i})).not.toBeInTheDocument()});
  it('shows a safe missing-user state',async()=>{go('/users/999','Admin',()=>json({detail:'SQL secret connection string'},404));expect(await screen.findByRole('heading',{name:'User not found'})).toBeInTheDocument();expect(screen.queryByText(/SQL|secret|connection string/i)).not.toBeInTheDocument()});
  it('creates with the exact DTO and backend role options',async()=>{let sent:Record<string,unknown>|undefined;go('/users/new','Admin',(url,init)=>{if(url.endsWith('/api/roles'))return json(roles);if(init?.method==='POST'){sent=JSON.parse(String(init.body)) as Record<string,unknown>;return json({...account,userId:3})}return json({...account,userId:3})});await screen.findByLabelText('Username');expect(screen.getByRole('option',{name:'Auditor'})).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Username'),{target:{value:'new-user'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'new@example.com'}});fireEvent.change(screen.getByLabelText('Full name'),{target:{value:'New User'}});fireEvent.change(screen.getByLabelText('Password'),{target:{value:'sixteen-character-password'}});fireEvent.change(screen.getByLabelText('Role'),{target:{value:'Auditor'}});fireEvent.click(screen.getByRole('button',{name:'Create user'}));await waitFor(()=>expect(sent).toEqual({username:'new-user',email:'new@example.com',fullName:'New User',role:'Auditor',isActive:true,password:'sixteen-character-password'}));expect(await screen.findByText('User created successfully.')).toBeInTheDocument();expect(screen.queryByDisplayValue('sixteen-character-password')).not.toBeInTheDocument()});
  it('maps create validation and duplicate email safely',async()=>{go('/users/new','Admin',(url,init)=>url.endsWith('/api/roles')?json(roles):init?.method==='POST'?json({message:'A user with this email already exists.'},409):json(account));await screen.findByLabelText('Username');fireEvent.change(screen.getByLabelText('Username'),{target:{value:'new-user'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'new@example.com'}});fireEvent.change(screen.getByLabelText('Full name'),{target:{value:'New User'}});fireEvent.change(screen.getByLabelText('Password'),{target:{value:'sixteen-character-password'}});fireEvent.click(screen.getByRole('button',{name:'Create user'}));expect(await screen.findByRole('alert')).toHaveTextContent('A user with this email already exists.')});
  it('edits only supported fields and sends no password',async()=>{let sent:Record<string,unknown>|undefined;go('/users/2/edit','Admin',(url,init)=>{if(url.endsWith('/api/roles'))return json(roles);if(init?.method==='PUT'){sent=JSON.parse(String(init.body)) as Record<string,unknown>;return json({...account,role:'Auditor',isActive:false})}return json(account)});await screen.findByDisplayValue('ada@example.com');expect(screen.queryByLabelText('Password')).not.toBeInTheDocument();fireEvent.change(screen.getByLabelText('Role'),{target:{value:'Auditor'}});fireEvent.click(screen.getByLabelText('Active user'));fireEvent.click(screen.getByRole('button',{name:'Save changes'}));await waitFor(()=>expect(sent).toEqual({username:'ada',email:'ada@example.com',fullName:'Ada User',role:'Auditor',isActive:false}));expect(sent).not.toHaveProperty('password')});
  it('shows backend last-admin conflict and does not bypass it',async()=>{const last={...account,userId:1,username:'admin',email:'admin@example.com',fullName:'Admin User',role:'Admin' as Role};go('/users/1/edit','Admin',(url,init)=>url.endsWith('/api/roles')?json(roles):init?.method==='PUT'?json({message:'The last active administrator cannot be deactivated or demoted.'},409):json(last));await screen.findByDisplayValue('Admin User');fireEvent.change(screen.getByLabelText('Role'),{target:{value:'Auditor'}});expect(screen.getByText(/At least one active Admin must remain/)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Save changes'}));expect(await screen.findByRole('alert')).toHaveTextContent('last active administrator')});
});
