import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom';
import { AuthProvider } from './auth/AuthContext';
import { DashboardLayout } from './layouts/DashboardLayout';
import { DashboardPage } from './pages/DashboardPage';
import { CustomersPage } from './pages/CustomersPage';
import { CustomerDetailPage } from './pages/CustomerDetailPage';
import { CustomerFormPage } from './pages/CustomerFormPage';
import { ProductsPage } from './pages/ProductsPage';
import { ProductDetailPage } from './pages/ProductDetailPage';
import { ProductFormPage } from './pages/ProductFormPage';
import { ContractsPage } from './pages/ContractsPage';
import { ContractDetailPage } from './pages/ContractDetailPage';
import { ContractFormPage } from './pages/ContractFormPage';
import { PaymentsPage } from './pages/PaymentsPage';
import { PaymentDetailPage } from './pages/PaymentDetailPage';
import { PaymentFormPage } from './pages/PaymentFormPage';
import { GuarantorsPage } from './pages/GuarantorsPage';
import { GuarantorDetailPage } from './pages/GuarantorDetailPage';
import { GuarantorFormPage } from './pages/GuarantorFormPage';
import { InstallmentsPage } from './pages/InstallmentsPage';
import { InstallmentDetailPage } from './pages/InstallmentDetailPage';
import { LoginPage } from './pages/LoginPage';
import { AccessDeniedPage, ComingSoonPage, NotFoundPage } from './pages/StatusPages';
import { ProtectedRoute } from './routes/ProtectedRoute';
const modules = ['collections', 'reports', 'users'];
export function App() { return <BrowserRouter><AuthProvider><Routes><Route path="/login" element={<LoginPage />} /><Route element={<ProtectedRoute />}><Route element={<DashboardLayout />}><Route path="/dashboard" element={<DashboardPage />} /><Route path="/customers" element={<CustomersPage />} /><Route path="/customers/new" element={<CustomerFormPage />} /><Route path="/customers/:id" element={<CustomerDetailPage />} /><Route path="/customers/:id/edit" element={<CustomerFormPage editing />} /><Route path="/products" element={<ProductsPage />} /><Route path="/products/new" element={<ProductFormPage />} /><Route path="/products/:id" element={<ProductDetailPage />} /><Route path="/products/:id/edit" element={<ProductFormPage editing />} /><Route path="/contracts" element={<ContractsPage />} /><Route path="/contracts/new" element={<ContractFormPage />} /><Route path="/contracts/:id" element={<ContractDetailPage />} /><Route path="/payments" element={<PaymentsPage />} /><Route path="/payments/new" element={<PaymentFormPage />} /><Route path="/payments/:id" element={<PaymentDetailPage />} /><Route path="/guarantors" element={<GuarantorsPage />} /><Route path="/guarantors/new" element={<GuarantorFormPage />} /><Route path="/guarantors/:id" element={<GuarantorDetailPage />} /><Route path="/guarantors/:id/edit" element={<GuarantorFormPage editing />} /><Route path="/installments" element={<InstallmentsPage />} /><Route path="/installments/:id" element={<InstallmentDetailPage />} />{modules.map(path => <Route key={path} path={`/${path}`} element={<ComingSoonPage />} />)}<Route path="/access-denied" element={<AccessDeniedPage />} /></Route></Route><Route path="/" element={<Navigate to="/dashboard" replace />} /><Route path="*" element={<NotFoundPage />} /></Routes></AuthProvider></BrowserRouter>; }
