import type { Role } from '../types/api';
export const canManageCustomers = (role: Role) => role === 'Admin' || role === 'Financial Manager' || role === 'Sales Agent';
export const canManageProducts = (role: Role) => role === 'Admin' || role === 'Financial Manager';
export const canCreateContracts = (role: Role) => role === 'Admin' || role === 'Financial Manager' || role === 'Sales Agent';
export const canActivateContracts = (role: Role) => role === 'Admin' || role === 'Financial Manager';
export const canCreatePayments = (role: Role) => role === 'Admin' || role === 'Financial Manager' || role === 'Collection Officer';
export const canReadPayments = (role: Role) => canCreatePayments(role) || role === 'Auditor';
export const canCreateGuarantors = (role: Role) => role === 'Admin' || role === 'Financial Manager' || role === 'Sales Agent';
export const canEditGuarantors = canCreateGuarantors;
export const canReadCollections = (role: Role) => role === 'Admin' || role === 'Financial Manager' || role === 'Collection Officer';
export const canReadCoreReports = (role: Role) => role === 'Admin' || role === 'Financial Manager' || role === 'Auditor';
export const canReadCollectionReports = (role: Role) => canReadCoreReports(role) || role === 'Collection Officer';
export const canReadReports = canReadCollectionReports;
